Methapolis: micropolisj.gui.JoinGameScreen Class Reference
micropolisj.gui.JoinGameScreen Class Reference
Public Member Functions
JoinGameScreen ()
void actionPerformed (ActionEvent ev)
Private Member Functions
void joinGame ()
void closeThis ()
Private Attributes
JButton loginBtn
JTextField textfield
Detailed Description
Definition at line 16 of file JoinGameScreen.java.
Constructor & Destructor Documentation
micropolisj.gui.JoinGameScreen.JoinGameScreen ()
Definition at line 20 of file JoinGameScreen.java.
References micropolisj.gui.JoinGameScreen.joinGame(), micropolisj.gui.JoinGameScreen.loginBtn, and micropolisj.gui.JoinGameScreen.textfield.
Member Function Documentation
void micropolisj.gui.JoinGameScreen.actionPerformed (ActionEvent ev)
Definition at line 59 of file JoinGameScreen.java.
References micropolisj.gui.JoinGameScreen.joinGame().
void micropolisj.gui.JoinGameScreen.closeThis () private
Definition at line 76 of file JoinGameScreen.java.
Referenced by micropolisj.gui.JoinGameScreen.joinGame().
void micropolisj.gui.JoinGameScreen.joinGame () private
Definition at line 63 of file JoinGameScreen.java.
References micropolisj.gui.JoinGameScreen.closeThis(), and micropolisj.gui.JoinGameScreen.textfield.
Referenced by micropolisj.gui.JoinGameScreen.actionPerformed(), and micropolisj.gui.JoinGameScreen.JoinGameScreen().
Member Data Documentation
JButton micropolisj.gui.JoinGameScreen.loginBtn private
Definition at line 17 of file JoinGameScreen.java.
Referenced by micropolisj.gui.JoinGameScreen.JoinGameScreen().
JTextField micropolisj.gui.JoinGameScreen.textfield private
Definition at line 18 of file JoinGameScreen.java.
Referenced by micropolisj.gui.JoinGameScreen.joinGame(), and micropolisj.gui.JoinGameScreen.JoinGameScreen().
The documentation for this class was generated from the following file:
src/micropolisj/gui/JoinGameScreen.java