Methapolis: micropolisj.gui.NotificationPane Class Reference
micropolisj.gui.NotificationPane Class Reference
Public Member Functions
NotificationPane (Micropolis engine)
void showMessage (Micropolis engine, MicropolisMessage msg, int xpos, int ypos)
void showZoneStatus (Micropolis engine, int xpos, int ypos, ZoneStatus zone)
Private Member Functions
void onDismissClicked ()
Detailed Description
Definition at line 19 of file NotificationPane.java.
Constructor & Destructor Documentation
micropolisj.gui.NotificationPane.NotificationPane (Micropolis engine)
Definition at line 33 of file NotificationPane.java.
References micropolisj.gui.NotificationPane.onDismissClicked().
Member Function Documentation
void micropolisj.gui.NotificationPane.onDismissClicked () private
Definition at line 72 of file NotificationPane.java.
Referenced by micropolisj.gui.NotificationPane.NotificationPane().
void micropolisj.gui.NotificationPane.showMessage (Micropolis engine, MicropolisMessage msg, int xpos, int ypos)
Definition at line 90 of file NotificationPane.java.
Referenced by micropolisj.gui.MainWindow.cityMessage().
void micropolisj.gui.NotificationPane.showZoneStatus (Micropolis engine, int xpos, int ypos, ZoneStatus zone)
Definition at line 112 of file NotificationPane.java.
References micropolisj.engine.ZoneStatus.building, micropolisj.engine.ZoneStatus.crimeLevel, micropolisj.engine.ZoneStatus.growthRate, micropolisj.engine.ZoneStatus.landValue, micropolisj.engine.ZoneStatus.pollution, and micropolisj.engine.ZoneStatus.popDensity.
The documentation for this class was generated from the following file:
src/micropolisj/gui/NotificationPane.java