Methapolis: micropolisj.gui.NewCityDialog Class Reference
micropolisj.gui.NewCityDialog Class Reference
Public Member Functions
NewCityDialog (MainWindow owner, boolean showCancelOption)
NewCityDialog (MainWindow owner, boolean showCancelOption, Micropolis engine)
Private Member Functions
void onPreviousMapClicked ()
void onNextMapClicked ()
void onLoadCityClicked ()
void onPlayClicked ()
void onCancelClicked ()
void onQuitClicked ()
int getSelectedGameLevel ()
void setGameLevel (int level)
Detailed Description
Definition at line 24 of file NewCityDialog.java.
Constructor & Destructor Documentation
micropolisj.gui.NewCityDialog.NewCityDialog (MainWindow owner, boolean showCancelOption)
Definition at line 35 of file NewCityDialog.java.
micropolisj.gui.NewCityDialog.NewCityDialog (MainWindow owner, boolean showCancelOption, Micropolis engine)
Definition at line 39 of file NewCityDialog.java.
References micropolisj.engine.Micropolis.getPlayerInfo(), micropolisj.engine.GameLevel.MAX_LEVEL, micropolisj.engine.GameLevel.MIN_LEVEL, micropolisj.gui.NewCityDialog.onCancelClicked(), micropolisj.gui.NewCityDialog.onLoadCityClicked(), micropolisj.gui.NewCityDialog.onNextMapClicked(), micropolisj.gui.NewCityDialog.onPlayClicked(), micropolisj.gui.NewCityDialog.onPreviousMapClicked(), micropolisj.gui.NewCityDialog.onQuitClicked(), micropolisj.engine.PlayerInfo.researchState, micropolisj.gui.NewCityDialog.setGameLevel(), micropolisj.engine.PlayerInfo.setResearchState(), micropolisj.research.ResearchState.toolBtns, and micropolisj.gui.MainWindow.toolBtns.
Member Function Documentation
int micropolisj.gui.NewCityDialog.getSelectedGameLevel () private
Definition at line 225 of file NewCityDialog.java.
References micropolisj.engine.GameLevel.MIN_LEVEL.
Referenced by micropolisj.gui.NewCityDialog.onPlayClicked().
void micropolisj.gui.NewCityDialog.onCancelClicked () private
Definition at line 215 of file NewCityDialog.java.
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog().
void micropolisj.gui.NewCityDialog.onLoadCityClicked () private
Definition at line 175 of file NewCityDialog.java.
References micropolisj.engine.Micropolis.load().
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog().
void micropolisj.gui.NewCityDialog.onNextMapClicked () private
Definition at line 159 of file NewCityDialog.java.
References micropolisj.gui.OverlayMapView.setEngine().
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog().
void micropolisj.gui.NewCityDialog.onPlayClicked () private
Definition at line 208 of file NewCityDialog.java.
References micropolisj.engine.Micropolis.gameLevel, micropolisj.gui.NewCityDialog.getSelectedGameLevel(), micropolisj.engine.GameLevel.getStartingFunds(), micropolisj.engine.Micropolis.setFunds(), and micropolisj.engine.Micropolis.setGameLevel().
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog().
void micropolisj.gui.NewCityDialog.onPreviousMapClicked () private
Definition at line 147 of file NewCityDialog.java.
References micropolisj.gui.OverlayMapView.setEngine().
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog().
void micropolisj.gui.NewCityDialog.onQuitClicked () private
Definition at line 220 of file NewCityDialog.java.
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog().
void micropolisj.gui.NewCityDialog.setGameLevel (int level) private
Definition at line 236 of file NewCityDialog.java.
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog().
The documentation for this class was generated from the following file:
src/micropolisj/gui/NewCityDialog.java