Methapolis: micropolisj.engine.MapGenerator Class Reference
micropolisj.engine.MapGenerator Class Reference
Classes
enum CreateIsland
Public Member Functions
MapGenerator (Micropolis engine)
void generateNewCity ()
void generateSomeCity (long r)
Private Member Functions
int getWidth ()
int getHeight ()
void makeIsland ()
int erand (int limit)
void makeNakedIsland ()
void clearMap ()
void getRandStart ()
void makeLakes ()
void doRivers ()
void doBRiv ()
void doSRiv ()
void BRivPlop ()
void SRivPlop ()
void putOnMap (char mapChar, int xoff, int yoff)
void smoothRiver ()
void doTrees ()
void treeSplash (int xloc, int yloc)
void moveMap (int dir)
void smoothTrees ()
Detailed Description
Contains the code for generating a random map terrain.
Definition at line 18 of file MapGenerator.java.
Constructor & Destructor Documentation
micropolisj.engine.MapGenerator.MapGenerator (Micropolis engine)
Definition at line 35 of file MapGenerator.java.
References micropolisj.engine.Micropolis.map.
Member Function Documentation
void micropolisj.engine.MapGenerator.BRivPlop () private
Definition at line 339 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.putOnMap().
Referenced by micropolisj.engine.MapGenerator.doBRiv(), micropolisj.engine.MapGenerator.makeLakes(), and micropolisj.engine.MapGenerator.makeNakedIsland().
void micropolisj.engine.MapGenerator.clearMap () private
Definition at line 185 of file MapGenerator.java.
void micropolisj.engine.MapGenerator.doBRiv () private
Definition at line 255 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.BRivPlop(), micropolisj.engine.MapGenerator.moveMap(), and micropolisj.engine.Micropolis.testBounds().
Referenced by micropolisj.engine.MapGenerator.doRivers().
void micropolisj.engine.MapGenerator.doRivers () private
Definition at line 239 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.doBRiv(), and micropolisj.engine.MapGenerator.doSRiv().
void micropolisj.engine.MapGenerator.doSRiv () private
Definition at line 291 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.moveMap(), micropolisj.engine.MapGenerator.SRivPlop(), and micropolisj.engine.Micropolis.testBounds().
Referenced by micropolisj.engine.MapGenerator.doRivers().
void micropolisj.engine.MapGenerator.doTrees () private
Definition at line 433 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.getHeight(), micropolisj.engine.MapGenerator.getWidth(), micropolisj.engine.MapGenerator.smoothTrees(), and micropolisj.engine.MapGenerator.treeSplash().
Referenced by micropolisj.engine.MapGenerator.makeIsland().
int micropolisj.engine.MapGenerator.erand (int limit) private
Definition at line 128 of file MapGenerator.java.
Referenced by micropolisj.engine.MapGenerator.makeNakedIsland().
void micropolisj.engine.MapGenerator.generateNewCity ()
Generate a random map terrain.
Definition at line 55 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.generateSomeCity().
void micropolisj.engine.MapGenerator.generateSomeCity (long r)
Definition at line 61 of file MapGenerator.java.
References micropolisj.engine.Micropolis.fireWholeMapChanged().
Referenced by micropolisj.engine.MapGenerator.generateNewCity().
int micropolisj.engine.MapGenerator.getHeight () private
Definition at line 47 of file MapGenerator.java.
Referenced by micropolisj.engine.MapGenerator.doTrees(), micropolisj.engine.MapGenerator.getRandStart(), micropolisj.engine.MapGenerator.makeLakes(), and micropolisj.engine.MapGenerator.makeNakedIsland().
void micropolisj.engine.MapGenerator.getRandStart () private
Definition at line 203 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.getHeight(), and micropolisj.engine.MapGenerator.getWidth().
int micropolisj.engine.MapGenerator.getWidth () private
Definition at line 42 of file MapGenerator.java.
Referenced by micropolisj.engine.MapGenerator.doTrees(), micropolisj.engine.MapGenerator.getRandStart(), micropolisj.engine.MapGenerator.makeLakes(), and micropolisj.engine.MapGenerator.makeNakedIsland().
void micropolisj.engine.MapGenerator.makeIsland () private
Definition at line 121 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.doTrees(), micropolisj.engine.MapGenerator.makeNakedIsland(), and micropolisj.engine.MapGenerator.smoothRiver().
void micropolisj.engine.MapGenerator.makeLakes () private
Definition at line 212 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.BRivPlop(), micropolisj.engine.MapGenerator.getHeight(), micropolisj.engine.MapGenerator.getWidth(), and micropolisj.engine.MapGenerator.SRivPlop().
void micropolisj.engine.MapGenerator.makeNakedIsland () private
Definition at line 136 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.BRivPlop(), micropolisj.engine.MapGenerator.erand(), micropolisj.engine.MapGenerator.getHeight(), micropolisj.engine.MapGenerator.getWidth(), and micropolisj.engine.MapGenerator.SRivPlop().
Referenced by micropolisj.engine.MapGenerator.makeIsland().
void micropolisj.engine.MapGenerator.moveMap (int dir) private
Definition at line 489 of file MapGenerator.java.
Referenced by micropolisj.engine.MapGenerator.doBRiv(), micropolisj.engine.MapGenerator.doSRiv(), and micropolisj.engine.MapGenerator.treeSplash().
void micropolisj.engine.MapGenerator.putOnMap (char mapChar, int xoff, int yoff) private
Definition at line 370 of file MapGenerator.java.
References micropolisj.engine.Micropolis.testBounds().
Referenced by micropolisj.engine.MapGenerator.BRivPlop(), and micropolisj.engine.MapGenerator.SRivPlop().
void micropolisj.engine.MapGenerator.smoothRiver () private
Definition at line 400 of file MapGenerator.java.
References micropolisj.engine.Micropolis.testBounds().
Referenced by micropolisj.engine.MapGenerator.makeIsland().
void micropolisj.engine.MapGenerator.smoothTrees () private
Definition at line 505 of file MapGenerator.java.
References micropolisj.engine.Micropolis.testBounds().
Referenced by micropolisj.engine.MapGenerator.doTrees().
void micropolisj.engine.MapGenerator.SRivPlop () private
Definition at line 359 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.putOnMap().
Referenced by micropolisj.engine.MapGenerator.doSRiv(), micropolisj.engine.MapGenerator.makeLakes(), and micropolisj.engine.MapGenerator.makeNakedIsland().
void micropolisj.engine.MapGenerator.treeSplash (int xloc, int yloc) private
Definition at line 457 of file MapGenerator.java.
References micropolisj.engine.MapGenerator.moveMap(), and micropolisj.engine.Micropolis.testBounds().
Referenced by micropolisj.engine.MapGenerator.doTrees().
The documentation for this class was generated from the following file:
src/micropolisj/engine/MapGenerator.java