Methapolis: micropolisj.gui.BudgetDialog Class Reference
micropolisj.gui.BudgetDialog Class Reference
Public Member Functions
BudgetDialog (Window owner, Micropolis engine)
Private Member Functions
void applyChange ()
void loadBudgetNumbers (boolean updateEntries)
void setAutoRequestFocus_compat (boolean v)
JComponent makeFundingRatesPane ()
JComponent makeOptionsPane ()
JComponent makeTaxPane ()
void onContinueClicked ()
void onResetClicked ()
JComponent makeBalancePane ()
Detailed Description
Definition at line 22 of file BudgetDialog.java.
Constructor & Destructor Documentation
micropolisj.gui.BudgetDialog.BudgetDialog (Window owner, Micropolis engine)
Definition at line 106 of file BudgetDialog.java.
References micropolisj.gui.BudgetDialog.applyChange(), micropolisj.gui.BudgetDialog.loadBudgetNumbers(), micropolisj.gui.BudgetDialog.makeBalancePane(), micropolisj.gui.BudgetDialog.makeFundingRatesPane(), micropolisj.gui.BudgetDialog.makeOptionsPane(), micropolisj.gui.BudgetDialog.makeTaxPane(), micropolisj.gui.BudgetDialog.onContinueClicked(), micropolisj.gui.BudgetDialog.onResetClicked(), and micropolisj.gui.BudgetDialog.setAutoRequestFocus_compat().
Member Function Documentation
void micropolisj.gui.BudgetDialog.applyChange () private
Definition at line 57 of file BudgetDialog.java.
References micropolisj.gui.BudgetDialog.loadBudgetNumbers(), and micropolisj.engine.Micropolis.setBudgetNumbers().
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
void micropolisj.gui.BudgetDialog.loadBudgetNumbers (boolean updateEntries) private
Definition at line 71 of file BudgetDialog.java.
References micropolisj.engine.Micropolis.generateBudget(), and micropolisj.engine.Micropolis.getPlayerInfo().
Referenced by micropolisj.gui.BudgetDialog.applyChange(), micropolisj.gui.BudgetDialog.BudgetDialog(), and micropolisj.gui.BudgetDialog.onResetClicked().
JComponent micropolisj.gui.BudgetDialog.makeBalancePane () private
Definition at line 339 of file BudgetDialog.java.
References micropolisj.engine.Micropolis.financialHistory.
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
JComponent micropolisj.gui.BudgetDialog.makeFundingRatesPane () private
Definition at line 206 of file BudgetDialog.java.
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
JComponent micropolisj.gui.BudgetDialog.makeOptionsPane () private
Definition at line 261 of file BudgetDialog.java.
References micropolisj.engine.Micropolis.autoBudget, micropolisj.engine.Speed.PAUSED, and micropolisj.engine.Micropolis.simSpeed.
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
JComponent micropolisj.gui.BudgetDialog.makeTaxPane () private
Definition at line 283 of file BudgetDialog.java.
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
void micropolisj.gui.BudgetDialog.onContinueClicked () private
Definition at line 314 of file BudgetDialog.java.
References micropolisj.engine.Micropolis.autoBudget, micropolisj.engine.Speed.NORMAL, micropolisj.engine.Speed.PAUSED, micropolisj.engine.Micropolis.setSpeed(), micropolisj.engine.Micropolis.simSpeed, and micropolisj.engine.Micropolis.toggleAutoBudget().
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
void micropolisj.gui.BudgetDialog.onResetClicked () private
Definition at line 329 of file BudgetDialog.java.
References micropolisj.engine.PlayerInfo.cityTax, micropolisj.engine.PlayerInfo.firePercent, micropolisj.engine.Micropolis.getPlayerInfo(), micropolisj.gui.BudgetDialog.loadBudgetNumbers(), micropolisj.engine.PlayerInfo.policePercent, micropolisj.engine.PlayerInfo.researchPercent, and micropolisj.engine.PlayerInfo.roadPercent.
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
void micropolisj.gui.BudgetDialog.setAutoRequestFocus_compat (boolean v) private
Definition at line 193 of file BudgetDialog.java.
Referenced by micropolisj.gui.BudgetDialog.BudgetDialog().
The documentation for this class was generated from the following file:
src/micropolisj/gui/BudgetDialog.java