Methapolis: micropolisj.gui.OverlayMapView Class Reference
micropolisj.gui.OverlayMapView Class Reference
Classes
class ConnectedView
Public Member Functions
OverlayMapView (Micropolis _engine)
Micropolis getEngine ()
void setEngine (Micropolis newEngine)
MapState getMapState ()
Dimension getPreferredSize ()
void setMapState (MapState newState)
void paintComponent (Graphics gr)
Dimension getPreferredScrollableViewportSize ()
int getScrollableBlockIncrement (Rectangle visibleRect, int orientation, int direction)
boolean getScrollableTracksViewportWidth ()
boolean getScrollableTracksViewportHeight ()
int getScrollableUnitIncrement (Rectangle visibleRect, int orientation, int direction)
void mapOverlayDataChanged (MapState overlayDataType)
void spriteMoved (Sprite sprite)
void tileChanged (int xpos, int ypos)
void wholeMapChanged ()
void dragViewToCityCenter ()
void connectView (MicropolisDrawingArea view, JScrollPane scrollPane)
Private Member Functions
Color getCI (int x)
Color getCI_rog (int x)
void drawPollutionMap (Graphics gr)
void drawCrimeMap (Graphics gr)
void drawPopDensity (Graphics gr)
void drawRateOfGrowth (Graphics gr)
void drawFireRadius (Graphics gr)
void drawPoliceRadius (Graphics gr)
void maybeDrawRect (Graphics gr, Color col, int x, int y, int width, int height)
int checkPower (BufferedImage img, int x, int y, int rawTile)
int checkLandValueOverlay (BufferedImage img, int xpos, int ypos, int tile)
int checkTrafficOverlay (BufferedImage img, int xpos, int ypos, int tile)
void dragViewTo (Point p)
void onMousePressed (MouseEvent ev)
void onMouseDragged (MouseEvent ev)
Detailed Description
Definition at line 22 of file OverlayMapView.java.
Constructor & Destructor Documentation
micropolisj.gui.OverlayMapView.OverlayMapView (Micropolis _engine)
Definition at line 29 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.onMouseDragged(), micropolisj.gui.OverlayMapView.onMousePressed(), and micropolisj.gui.OverlayMapView.setEngine().
Member Function Documentation
int micropolisj.gui.OverlayMapView.checkLandValueOverlay (BufferedImage img, int xpos, int ypos, int tile) private
Definition at line 259 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.getCI(), and micropolisj.engine.Micropolis.getLandValue().
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
int micropolisj.gui.OverlayMapView.checkPower (BufferedImage img, int x, int y, int rawTile) private
Definition at line 230 of file OverlayMapView.java.
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
int micropolisj.gui.OverlayMapView.checkTrafficOverlay (BufferedImage img, int xpos, int ypos, int tile) private
Definition at line 279 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.getCI(), and micropolisj.engine.Micropolis.getTrafficDensity().
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
void micropolisj.gui.OverlayMapView.connectView (MicropolisDrawingArea view, JScrollPane scrollPane)
Definition at line 540 of file OverlayMapView.java.
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.OverlayMapView.dragViewTo (Point p) private
Definition at line 435 of file OverlayMapView.java.
Referenced by micropolisj.gui.OverlayMapView.dragViewToCityCenter(), micropolisj.gui.OverlayMapView.onMouseDragged(), and micropolisj.gui.OverlayMapView.onMousePressed().
void micropolisj.gui.OverlayMapView.dragViewToCityCenter ()
Definition at line 516 of file OverlayMapView.java.
References micropolisj.engine.PlayerInfo.centerMassX, micropolisj.engine.PlayerInfo.centerMassY, micropolisj.gui.OverlayMapView.dragViewTo(), and micropolisj.engine.Micropolis.getPlayerInfo().
Referenced by micropolisj.gui.OverlayMapView.setEngine(), and micropolisj.gui.OverlayMapView.wholeMapChanged().
void micropolisj.gui.OverlayMapView.drawCrimeMap (Graphics gr) private
Definition at line 163 of file OverlayMapView.java.
References micropolisj.engine.Micropolis.crimeMem, micropolisj.gui.OverlayMapView.getCI(), and micropolisj.gui.OverlayMapView.maybeDrawRect().
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
void micropolisj.gui.OverlayMapView.drawFireRadius (Graphics gr) private
Definition at line 196 of file OverlayMapView.java.
References micropolisj.engine.Micropolis.fireRate, micropolisj.gui.OverlayMapView.getCI(), and micropolisj.gui.OverlayMapView.maybeDrawRect().
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
void micropolisj.gui.OverlayMapView.drawPoliceRadius (Graphics gr) private
Definition at line 207 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.getCI(), micropolisj.gui.OverlayMapView.maybeDrawRect(), and micropolisj.engine.Micropolis.policeMapEffect.
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
void micropolisj.gui.OverlayMapView.drawPollutionMap (Graphics gr) private
Definition at line 152 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.getCI(), micropolisj.gui.OverlayMapView.maybeDrawRect(), and micropolisj.engine.Micropolis.pollutionMem.
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
void micropolisj.gui.OverlayMapView.drawPopDensity (Graphics gr) private
Definition at line 174 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.getCI(), micropolisj.gui.OverlayMapView.maybeDrawRect(), and micropolisj.engine.Micropolis.popDensity.
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
void micropolisj.gui.OverlayMapView.drawRateOfGrowth (Graphics gr) private
Definition at line 185 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.getCI_rog(), micropolisj.gui.OverlayMapView.maybeDrawRect(), and micropolisj.engine.Micropolis.rateOGMem.
Referenced by micropolisj.gui.OverlayMapView.paintComponent().
Color micropolisj.gui.OverlayMapView.getCI (int x) private
Definition at line 124 of file OverlayMapView.java.
Referenced by micropolisj.gui.OverlayMapView.checkLandValueOverlay(), micropolisj.gui.OverlayMapView.checkTrafficOverlay(), micropolisj.gui.OverlayMapView.drawCrimeMap(), micropolisj.gui.OverlayMapView.drawFireRadius(), micropolisj.gui.OverlayMapView.drawPoliceRadius(), micropolisj.gui.OverlayMapView.drawPollutionMap(), and micropolisj.gui.OverlayMapView.drawPopDensity().
Color micropolisj.gui.OverlayMapView.getCI_rog (int x) private
Definition at line 138 of file OverlayMapView.java.
Referenced by micropolisj.gui.OverlayMapView.drawRateOfGrowth().
Micropolis micropolisj.gui.OverlayMapView.getEngine ()
Definition at line 51 of file OverlayMapView.java.
MapState micropolisj.gui.OverlayMapView.getMapState ()
Definition at line 74 of file OverlayMapView.java.
Referenced by micropolisj.gui.MainWindow.setMapState().
Dimension micropolisj.gui.OverlayMapView.getPreferredScrollableViewportSize ()
Definition at line 455 of file OverlayMapView.java.
Dimension micropolisj.gui.OverlayMapView.getPreferredSize ()
Definition at line 80 of file OverlayMapView.java.
References micropolisj.engine.Micropolis.getHeight(), and micropolisj.engine.Micropolis.getWidth().
int micropolisj.gui.OverlayMapView.getScrollableBlockIncrement (Rectangle visibleRect, int orientation, int direction)
Definition at line 461 of file OverlayMapView.java.
boolean micropolisj.gui.OverlayMapView.getScrollableTracksViewportHeight ()
Definition at line 476 of file OverlayMapView.java.
boolean micropolisj.gui.OverlayMapView.getScrollableTracksViewportWidth ()
Definition at line 470 of file OverlayMapView.java.
int micropolisj.gui.OverlayMapView.getScrollableUnitIncrement (Rectangle visibleRect, int orientation, int direction)
Definition at line 482 of file OverlayMapView.java.
void micropolisj.gui.OverlayMapView.mapOverlayDataChanged (MapState overlayDataType)
Definition at line 491 of file OverlayMapView.java.
void micropolisj.gui.OverlayMapView.maybeDrawRect (Graphics gr, Color col, int x, int y, int width, int height) private
Definition at line 218 of file OverlayMapView.java.
Referenced by micropolisj.gui.OverlayMapView.drawCrimeMap(), micropolisj.gui.OverlayMapView.drawFireRadius(), micropolisj.gui.OverlayMapView.drawPoliceRadius(), micropolisj.gui.OverlayMapView.drawPollutionMap(), micropolisj.gui.OverlayMapView.drawPopDensity(), and micropolisj.gui.OverlayMapView.drawRateOfGrowth().
void micropolisj.gui.OverlayMapView.onMouseDragged (MouseEvent ev) private
Definition at line 553 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.dragViewTo().
Referenced by micropolisj.gui.OverlayMapView.OverlayMapView().
void micropolisj.gui.OverlayMapView.onMousePressed (MouseEvent ev) private
Definition at line 547 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.dragViewTo().
Referenced by micropolisj.gui.OverlayMapView.OverlayMapView().
void micropolisj.gui.OverlayMapView.paintComponent (Graphics gr)
Definition at line 300 of file OverlayMapView.java.
References micropolisj.gui.OverlayMapView.checkLandValueOverlay(), micropolisj.gui.OverlayMapView.checkPower(), micropolisj.gui.OverlayMapView.checkTrafficOverlay(), micropolisj.gui.OverlayMapView.drawCrimeMap(), micropolisj.gui.OverlayMapView.drawFireRadius(), micropolisj.gui.OverlayMapView.drawPoliceRadius(), micropolisj.gui.OverlayMapView.drawPollutionMap(), micropolisj.gui.OverlayMapView.drawPopDensity(), micropolisj.gui.OverlayMapView.drawRateOfGrowth(), micropolisj.engine.Micropolis.getHeight(), micropolisj.engine.Micropolis.getTile(), micropolisj.engine.Micropolis.getWidth(), and micropolisj.engine.MapState.TRAFFIC_OVERLAY.
void micropolisj.gui.OverlayMapView.setEngine (Micropolis newEngine)
Definition at line 56 of file OverlayMapView.java.
References micropolisj.engine.Micropolis.addMapListener(), micropolisj.engine.Micropolis.calculateCenterMass(), micropolisj.gui.OverlayMapView.dragViewToCityCenter(), and micropolisj.engine.Micropolis.removeMapListener().
Referenced by micropolisj.gui.MainWindow.MainWindow(), micropolisj.gui.NewCityDialog.onNextMapClicked(), micropolisj.gui.NewCityDialog.onPreviousMapClicked(), micropolisj.gui.OverlayMapView.OverlayMapView(), and micropolisj.gui.MainWindow.setEngine().
void micropolisj.gui.OverlayMapView.setMapState (MapState newState)
Definition at line 88 of file OverlayMapView.java.
Referenced by micropolisj.gui.MainWindow.setMapState().
void micropolisj.gui.OverlayMapView.spriteMoved (Sprite sprite)
Definition at line 497 of file OverlayMapView.java.
void micropolisj.gui.OverlayMapView.tileChanged (int xpos, int ypos)
Definition at line 502 of file OverlayMapView.java.
void micropolisj.gui.OverlayMapView.wholeMapChanged ()
Definition at line 509 of file OverlayMapView.java.
References micropolisj.engine.Micropolis.calculateCenterMass(), and micropolisj.gui.OverlayMapView.dragViewToCityCenter().
The documentation for this class was generated from the following file:
src/micropolisj/gui/OverlayMapView.java