Methapolis: micropolisj.engine.TileBehavior Class Reference
micropolisj.engine.TileBehavior Class Reference
Public Member Functions
final void processTile (int xpos, int ypos)
abstract void apply ()
Protected Member Functions
TileBehavior (Micropolis city)
Protected Attributes
final Micropolis city
final Random PRNG
Detailed Description
Definition at line 14 of file TileBehavior.java.
Constructor & Destructor Documentation
micropolisj.engine.TileBehavior.TileBehavior (Micropolis city) protected
Definition at line 23 of file TileBehavior.java.
References micropolisj.engine.TileBehavior.city, and micropolisj.engine.TileBehavior.PRNG.
Member Function Documentation
abstract void micropolisj.engine.TileBehavior.apply () pure virtual
Activate the tile identified by xpos and ypos properties.
Referenced by micropolisj.engine.TileBehavior.processTile().
final void micropolisj.engine.TileBehavior.processTile (int xpos, int ypos)
Definition at line 28 of file TileBehavior.java.
References micropolisj.engine.TileBehavior.apply(), micropolisj.engine.TileBehavior.city, and micropolisj.engine.Micropolis.getTileRaw().
Member Data Documentation
final Micropolis micropolisj.engine.TileBehavior.city protected
Definition at line 15 of file TileBehavior.java.
Referenced by micropolisj.engine.TileBehavior.processTile(), and micropolisj.engine.TileBehavior.TileBehavior().
final Random micropolisj.engine.TileBehavior.PRNG protected
Definition at line 16 of file TileBehavior.java.
Referenced by micropolisj.engine.TileBehavior.TileBehavior().
The documentation for this class was generated from the following file:
src/micropolisj/engine/TileBehavior.java