Methapolis: micropolisj.engine.TileSpec Class Reference
micropolisj.engine.TileSpec Class Reference
Classes
class BuildingInfo
class Scanner
Public Member Functions
String getAttribute (String key)
boolean getBooleanAttribute (String key)
BuildingInfo getBuildingInfo ()
CityDimension getBuildingSize ()
int getDescriptionNumber ()
String[] getImages ()
int getPollutionValue (Micropolis city)
int getPopulation ()
String toString ()
Static Public Member Functions
static TileSpec parse (int tileNumber, String inStr, Properties tilesRc)
static String[] generateTileNames (Properties recipe)
Public Attributes
TileSpec owner
int ownerOffsetX
int ownerOffsetY
Protected Member Functions
TileSpec (int tileNumber)
void load (String inStr, Properties tilesRc)
Private Member Functions
void resolveBuildingInfo (Map< String, TileSpec > tileMap)
int usePollutionResearch (int pollutionValue, Micropolis city)
void handleBuildingPart (String text, Map< String, TileSpec > tileMap)
Static Private Attributes
static final int POLLUTION_FACTOR = 25
Detailed Description
Definition at line 17 of file TileSpec.java.
Constructor & Destructor Documentation
micropolisj.engine.TileSpec.TileSpec (int tileNumber) protected
Definition at line 39 of file TileSpec.java.
Referenced by micropolisj.engine.TileSpec.parse().
Member Function Documentation
static String [] micropolisj.engine.TileSpec.generateTileNames (Properties recipe) static
Definition at line 324 of file TileSpec.java.
String micropolisj.engine.TileSpec.getAttribute (String key)
Definition at line 51 of file TileSpec.java.
Referenced by micropolisj.engine.TileSpec.getBooleanAttribute(), micropolisj.engine.TileSpec.getDescriptionNumber(), micropolisj.engine.TileSpec.getPollutionValue(), micropolisj.engine.TileSpec.getPopulation(), micropolisj.engine.TileConstants.getTileBehavior(), and micropolisj.engine.TileSpec.resolveBuildingInfo().
boolean micropolisj.engine.TileSpec.getBooleanAttribute (String key)
Definition at line 55 of file TileSpec.java.
References micropolisj.engine.TileSpec.getAttribute().
Referenced by micropolisj.engine.TileConstants.isCommercialZone(), micropolisj.engine.TileConstants.isIndustrialZone(), micropolisj.engine.TileConstants.isResidentialZoneAny(), and micropolisj.engine.TileSpec.load().
BuildingInfo micropolisj.engine.TileSpec.getBuildingInfo ()
Definition at line 67 of file TileSpec.java.
CityDimension micropolisj.engine.TileSpec.getBuildingSize ()
Definition at line 102 of file TileSpec.java.
Referenced by micropolisj.engine.TileConstants.getZoneSizeFor().
int micropolisj.engine.TileSpec.getDescriptionNumber ()
Definition at line 111 of file TileSpec.java.
References micropolisj.engine.TileSpec.getAttribute(), micropolisj.engine.TileSpec.getDescriptionNumber(), and micropolisj.engine.TileSpec.owner.
Referenced by micropolisj.engine.TileSpec.getDescriptionNumber(), and micropolisj.engine.TileConstants.getDescriptionNumber().
String [] micropolisj.engine.TileSpec.getImages ()
Definition at line 122 of file TileSpec.java.
int micropolisj.engine.TileSpec.getPollutionValue (Micropolis city)
Definition at line 132 of file TileSpec.java.
References micropolisj.engine.TileSpec.getAttribute(), micropolisj.engine.TileSpec.getPollutionValue(), micropolisj.engine.TileSpec.owner, and micropolisj.engine.TileSpec.usePollutionResearch().
Referenced by micropolisj.engine.TileSpec.getPollutionValue(), and micropolisj.engine.TileConstants.getPollutionValue().
int micropolisj.engine.TileSpec.getPopulation ()
Definition at line 146 of file TileSpec.java.
References micropolisj.engine.TileSpec.getAttribute().
Referenced by micropolisj.engine.TileConstants.commercialZonePop(), micropolisj.engine.TileConstants.industrialZonePop(), and micropolisj.engine.TileConstants.residentialZonePop().
void micropolisj.engine.TileSpec.handleBuildingPart (String text, Map< String, TileSpec > tileMap) private
Definition at line 310 of file TileSpec.java.
References micropolisj.engine.TileSpec.owner, micropolisj.engine.TileSpec.ownerOffsetX, and micropolisj.engine.TileSpec.ownerOffsetY.
void micropolisj.engine.TileSpec.load (String inStr, Properties tilesRc) protected
Definition at line 156 of file TileSpec.java.
References micropolisj.engine.TileSpec.getBooleanAttribute().
Referenced by micropolisj.engine.TileSpec.parse().
static TileSpec micropolisj.engine.TileSpec.parse (int tileNumber, String inStr, Properties tilesRc) static
Definition at line 45 of file TileSpec.java.
References micropolisj.engine.TileSpec.load(), and micropolisj.engine.TileSpec.TileSpec().
Referenced by micropolisj.build_tool.MakeTiles.main().
void micropolisj.engine.TileSpec.resolveBuildingInfo (Map< String, TileSpec > tileMap) private
Definition at line 71 of file TileSpec.java.
References micropolisj.engine.TileSpec.getAttribute().
String micropolisj.engine.TileSpec.toString ()
Definition at line 285 of file TileSpec.java.
int micropolisj.engine.TileSpec.usePollutionResearch (int pollutionValue, Micropolis city) private
Definition at line 128 of file TileSpec.java.
References micropolisj.research.ResearchData.environmentResearch, micropolisj.engine.Micropolis.playerInfo, micropolisj.engine.TileSpec.POLLUTION_FACTOR, and micropolisj.engine.PlayerInfo.researchData.
Referenced by micropolisj.engine.TileSpec.getPollutionValue().
Member Data Documentation
TileSpec micropolisj.engine.TileSpec.owner
Definition at line 27 of file TileSpec.java.
Referenced by micropolisj.engine.TileSpec.getDescriptionNumber(), micropolisj.engine.TileSpec.getPollutionValue(), micropolisj.engine.TileSpec.handleBuildingPart(), micropolisj.engine.TileConstants.isCommercialZone(), micropolisj.engine.TileConstants.isIndustrialZone(), and micropolisj.engine.TileConstants.isResidentialZoneAny().
int micropolisj.engine.TileSpec.ownerOffsetX
Definition at line 28 of file TileSpec.java.
Referenced by micropolisj.engine.TileSpec.handleBuildingPart().
int micropolisj.engine.TileSpec.ownerOffsetY
Definition at line 29 of file TileSpec.java.
Referenced by micropolisj.engine.TileSpec.handleBuildingPart().
final int micropolisj.engine.TileSpec.POLLUTION_FACTOR = 25 static private
Definition at line 37 of file TileSpec.java.
Referenced by micropolisj.engine.TileSpec.usePollutionResearch().
The documentation for this class was generated from the following file:
src/micropolisj/engine/TileSpec.java