Methapolis: micropolisj.gui.DemandIndicator Class Reference
micropolisj.gui.DemandIndicator Class Reference
Public Member Functions
DemandIndicator ()
void setEngine (Micropolis newEngine)
Dimension getMinimumSize ()
Dimension getPreferredSize ()
Dimension getMaximumSize ()
void paintComponent (Graphics gr1)
void demandChanged ()
void cityMessage (MicropolisMessage m, CityLocation p)
void citySound (Sound sound, CityLocation p)
void censusChanged ()
void evaluationChanged ()
void fundsChanged ()
void optionsChanged ()
Detailed Description
Definition at line 18 of file DemandIndicator.java.
Constructor & Destructor Documentation
micropolisj.gui.DemandIndicator.DemandIndicator ()
Definition at line 23 of file DemandIndicator.java.
Member Function Documentation
void micropolisj.gui.DemandIndicator.censusChanged ()
Fired whenever the "census" is taken, and the various historical counters have been updated. (Once a month in game.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 148 of file DemandIndicator.java.
void micropolisj.gui.DemandIndicator.cityMessage (MicropolisMessage m, CityLocation p)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 146 of file DemandIndicator.java.
void micropolisj.gui.DemandIndicator.citySound (Sound sound, CityLocation p)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 147 of file DemandIndicator.java.
void micropolisj.gui.DemandIndicator.demandChanged ()
Fired whenever playerInfo.resValve, playerInfo.comValve, or playerInfo.indValve changes. (Twice a month in game.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 140 of file DemandIndicator.java.
void micropolisj.gui.DemandIndicator.evaluationChanged ()
Fired whenever the city playerInfo.evaluation is recalculated. (Once a year.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 149 of file DemandIndicator.java.
void micropolisj.gui.DemandIndicator.fundsChanged ()
Fired whenever the mayor's money changes.
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 150 of file DemandIndicator.java.
Dimension micropolisj.gui.DemandIndicator.getMaximumSize ()
Definition at line 73 of file DemandIndicator.java.
Dimension micropolisj.gui.DemandIndicator.getMinimumSize ()
Definition at line 61 of file DemandIndicator.java.
Dimension micropolisj.gui.DemandIndicator.getPreferredSize ()
Definition at line 67 of file DemandIndicator.java.
void micropolisj.gui.DemandIndicator.optionsChanged ()
Fired whenever autoBulldoze, autoBudget, noDisasters, or simSpeed change.
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 151 of file DemandIndicator.java.
void micropolisj.gui.DemandIndicator.paintComponent (Graphics gr1)
Definition at line 86 of file DemandIndicator.java.
References micropolisj.engine.Micropolis.getComValve(), micropolisj.engine.Micropolis.getIndValve(), and micropolisj.engine.Micropolis.getResValve().
void micropolisj.gui.DemandIndicator.setEngine (Micropolis newEngine)
Definition at line 27 of file DemandIndicator.java.
References micropolisj.engine.Micropolis.addListener(), and micropolisj.engine.Micropolis.removeListener().
Referenced by micropolisj.gui.MainWindow.setEngine().
The documentation for this class was generated from the following file:
src/micropolisj/gui/DemandIndicator.java