Methapolis: micropolisj.gui.MainWindow Class Reference
micropolisj.gui.MainWindow Class Reference
Classes
class EarthquakeStepper
Public Member Functions
MainWindow ()
MainWindow (Micropolis engine)
void setEngine (Micropolis newEngine)
void onLoadGameClicked ()
void doNewCity (boolean firstTime)
void showToolResult (CityLocation loc, ToolResult result)
void earthquakeStarted ()
void cityMessage (MicropolisMessage m, CityLocation p)
void fundsChanged ()
void optionsChanged ()
void citySound (Sound sound, CityLocation loc)
void censusChanged ()
void demandChanged ()
void evaluationChanged ()
boolean dispatchKeyEvent (KeyEvent e)
void onCountdown (int count)
void onEnd ()
Static Public Member Functions
static String formatFunds (int funds)
static String formatGameDate (int cityTime)
Public Attributes
Map< MicropolisTool,
JToggleButton > toolBtns
Private Member Functions
void setupKeys (JMenu menu, String prefix)
void setupKeys (JMenuItem menuItem, String prefix)
void makeMenu ()
Micropolis getEngine ()
void onAutoBudgetClicked ()
void onAutoBulldozeClicked ()
void onDisastersClicked ()
void onSoundClicked ()
boolean onSaveCityClicked ()
boolean onSaveCityAsClicked ()
JToggleButton makeToolBtn (final MicropolisTool tool)
JToolBar makeToolbar ()
void selectTool (MicropolisTool newTool)
void onNewCityClicked ()
void doZoom (int dir, Point mousePt)
void doZoom (int dir)
void onMouseWheelMoved (MouseWheelEvent evt)
void onToolDown (MouseEvent ev)
void onToolUp (MouseEvent ev)
void onEscapePressed ()
void onToolDrag (MouseEvent ev)
void onToolHover (MouseEvent ev)
void onToolExited (MouseEvent ev)
void updateDateLabel ()
void startTimer ()
void showErrorMessage (Throwable e)
void stopTimer ()
void onWindowClosed (WindowEvent ev)
void onDifficultyClicked (int newDifficulty)
void onPriorityClicked (Speed newSpeed)
void onInvokeDisasterClicked (Disaster disaster)
void reloadFunds ()
void reloadOptions ()
void showAutoBudget ()
void showBudgetWindow (boolean isEndOfYear)
JMenuItem makeMapStateMenuItem (String stringPrefix, final MapState state)
void setMapState (MapState state)
void setMapLegend (MapState state)
void onLaunchTranslationToolClicked ()
void onAboutClicked ()
Static Private Attributes
static final int SCROLLING_SPEED = 100
Detailed Description
Definition at line 95 of file MainWindow.java.
Constructor & Destructor Documentation
micropolisj.gui.MainWindow.MainWindow ()
Definition at line 135 of file MainWindow.java.
micropolisj.gui.MainWindow.MainWindow (Micropolis engine)
Definition at line 139 of file MainWindow.java.
References micropolisj.engine.Micropolis.addEarthquakeListener(), micropolisj.engine.Micropolis.addListener(), micropolisj.engine.Micropolis.addTempelListener(), micropolisj.engine.MapState.ALL, micropolisj.engine.Sound.BG_MUSIC, micropolisj.engine.MapState.COMMERCIAL, micropolisj.gui.OverlayMapView.connectView(), micropolisj.engine.MapState.CRIME_OVERLAY, micropolisj.gui.MainWindow.doZoom(), micropolisj.engine.MapState.FIRE_OVERLAY, micropolisj.engine.Micropolis.getPlayerInfo(), micropolisj.engine.MapState.GROWTHRATE_OVERLAY, micropolisj.engine.MapState.INDUSTRIAL, micropolisj.engine.MapState.LANDVALUE_OVERLAY, micropolisj.engine.Micropolis.mainWindow, micropolisj.gui.MainWindow.makeMapStateMenuItem(), micropolisj.gui.MainWindow.makeMenu(), micropolisj.gui.MainWindow.makeToolbar(), micropolisj.gui.MainWindow.onEscapePressed(), micropolisj.gui.MainWindow.onMouseWheelMoved(), micropolisj.gui.MainWindow.onToolDown(), micropolisj.gui.MainWindow.onToolDrag(), micropolisj.gui.MainWindow.onToolExited(), micropolisj.gui.MainWindow.onToolHover(), micropolisj.gui.MainWindow.onToolUp(), micropolisj.gui.MainWindow.onWindowClosed(), micropolisj.engine.Micropolis.playerInfo, micropolisj.engine.MapState.POLICE_OVERLAY, micropolisj.engine.MapState.POLLUTE_OVERLAY, micropolisj.engine.MapState.POPDEN_OVERLAY, micropolisj.engine.MapState.POWER_OVERLAY, micropolisj.gui.MainWindow.reloadFunds(), micropolisj.gui.MainWindow.reloadOptions(), micropolisj.engine.PlayerInfo.researchState, micropolisj.engine.MapState.RESIDENTIAL, micropolisj.engine.MicropolisTool.ROCKET, micropolisj.gui.OverlayMapView.setEngine(), micropolisj.gui.MainWindow.setMapState(), micropolisj.research.ResearchState.setToolBtns(), micropolisj.gui.MainWindow.setupKeys(), micropolisj.gui.MainWindow.showErrorMessage(), micropolisj.gui.MainWindow.startTimer(), micropolisj.gui.MainWindow.toolBtns, micropolisj.engine.MapState.TRAFFIC_OVERLAY, and micropolisj.engine.MapState.TRANSPORT.
Member Function Documentation
void micropolisj.gui.MainWindow.censusChanged ()
Fired whenever the "census" is taken, and the various historical counters have been updated. (Once a month in game.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 1633 of file MainWindow.java.
void micropolisj.gui.MainWindow.cityMessage (MicropolisMessage m, CityLocation p)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 1573 of file MainWindow.java.
References micropolisj.gui.MessagesPane.appendCityMessage(), micropolisj.gui.NotificationPane.showMessage(), micropolisj.engine.MicropolisMessage.useNotificationPane, micropolisj.engine.CityLocation.x, and micropolisj.engine.CityLocation.y.
void micropolisj.gui.MainWindow.citySound (Sound sound, CityLocation loc)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 1606 of file MainWindow.java.
References micropolisj.engine.Sound.getAudioFile(), micropolisj.gui.MicropolisDrawingArea.getTileBounds(), micropolisj.engine.Sound.HONKHONK_LOW, micropolisj.engine.CityLocation.x, and micropolisj.engine.CityLocation.y.
Referenced by micropolisj.gui.MainWindow.showToolResult().
void micropolisj.gui.MainWindow.demandChanged ()
Fired whenever playerInfo.resValve, playerInfo.comValve, or playerInfo.indValve changes. (Twice a month in game.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 1636 of file MainWindow.java.
boolean micropolisj.gui.MainWindow.dispatchKeyEvent (KeyEvent e)
called whenever a key is pressed in mainwindow
Definition at line 1746 of file MainWindow.java.
References micropolisj.util.Utilities.moveRectangle(), micropolisj.gui.MainWindow.SCROLLING_SPEED, and micropolisj.gui.MainWindow.toolBtns.
void micropolisj.gui.MainWindow.doNewCity (boolean firstTime)
Definition at line 1139 of file MainWindow.java.
References micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.stopTimer().
Referenced by micropolisj.gui.MainWindow.onNewCityClicked(), micropolisj.gui.EndGamePane.startNewGame(), micropolisj.gui.SplashScreen.startNewGame(), micropolisj.gui.EndGamePane.startNewServer(), and micropolisj.gui.SplashScreen.startNewServer().
void micropolisj.gui.MainWindow.doZoom (int dir, Point mousePt) private
Definition at line 1160 of file MainWindow.java.
References micropolisj.gui.MicropolisDrawingArea.getTileSize(), and micropolisj.gui.MicropolisDrawingArea.selectTileSize().
Referenced by micropolisj.gui.MainWindow.doZoom(), micropolisj.gui.MainWindow.MainWindow(), micropolisj.gui.MainWindow.makeMenu(), and micropolisj.gui.MainWindow.onMouseWheelMoved().
void micropolisj.gui.MainWindow.doZoom (int dir) private
Definition at line 1183 of file MainWindow.java.
References micropolisj.gui.MainWindow.doZoom().
void micropolisj.gui.MainWindow.earthquakeStarted ()
Implements micropolisj.engine.EarthquakeListener.
Definition at line 1489 of file MainWindow.java.
References micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.stopTimer().
void micropolisj.gui.MainWindow.evaluationChanged ()
Fired whenever the city playerInfo.evaluation is recalculated. (Once a year.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 1639 of file MainWindow.java.
static String micropolisj.gui.MainWindow.formatFunds (int funds) static
Definition at line 1361 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.reloadFunds(), and micropolisj.gui.MainWindow.selectTool().
static String micropolisj.gui.MainWindow.formatGameDate (int cityTime) static
Definition at line 1365 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.updateDateLabel().
void micropolisj.gui.MainWindow.fundsChanged ()
Fired whenever the mayor's money changes.
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 1582 of file MainWindow.java.
References micropolisj.gui.MainWindow.reloadFunds().
Micropolis micropolisj.gui.MainWindow.getEngine () private
Definition at line 823 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.onAutoBudgetClicked(), micropolisj.gui.MainWindow.onAutoBulldozeClicked(), micropolisj.gui.MainWindow.onDifficultyClicked(), micropolisj.gui.MainWindow.onDisastersClicked(), micropolisj.gui.MainWindow.onInvokeDisasterClicked(), micropolisj.gui.MainWindow.onLoadGameClicked(), micropolisj.gui.MainWindow.onPriorityClicked(), micropolisj.gui.MainWindow.onSaveCityAsClicked(), micropolisj.gui.MainWindow.onSaveCityClicked(), micropolisj.gui.MainWindow.reloadFunds(), micropolisj.gui.MainWindow.reloadOptions(), micropolisj.gui.MainWindow.showBudgetWindow(), micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.updateDateLabel().
JMenuItem micropolisj.gui.MainWindow.makeMapStateMenuItem (String stringPrefix, final MapState state) private
Definition at line 1685 of file MainWindow.java.
References micropolisj.gui.MainWindow.setMapState(), and micropolisj.gui.MainWindow.setupKeys().
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.makeMenu () private
Definition at line 516 of file MainWindow.java.
References micropolisj.gui.MainWindow.doZoom(), micropolisj.engine.Disaster.EARTHQUAKE, micropolisj.engine.Speed.FAST, micropolisj.engine.Disaster.FIRE, micropolisj.engine.Disaster.FLOOD, micropolisj.engine.GameLevel.MAX_LEVEL, micropolisj.engine.Disaster.MELTDOWN, micropolisj.engine.GameLevel.MIN_LEVEL, micropolisj.engine.Disaster.MONSTER, micropolisj.engine.Speed.NORMAL, micropolisj.gui.MainWindow.onAboutClicked(), micropolisj.gui.MainWindow.onAutoBudgetClicked(), micropolisj.gui.MainWindow.onAutoBulldozeClicked(), micropolisj.gui.MainWindow.onDifficultyClicked(), micropolisj.gui.MainWindow.onDisastersClicked(), micropolisj.gui.MainWindow.onInvokeDisasterClicked(), micropolisj.gui.MainWindow.onLaunchTranslationToolClicked(), micropolisj.gui.MainWindow.onLoadGameClicked(), micropolisj.gui.MainWindow.onNewCityClicked(), micropolisj.gui.MainWindow.onPriorityClicked(), micropolisj.gui.MainWindow.onSaveCityAsClicked(), micropolisj.gui.MainWindow.onSaveCityClicked(), micropolisj.gui.MainWindow.onSoundClicked(), micropolisj.engine.Speed.PAUSED, micropolisj.gui.MainWindow.setupKeys(), micropolisj.engine.Speed.SLOW, micropolisj.engine.Speed.SUPER_FAST, and micropolisj.engine.Disaster.TORNADO.
Referenced by micropolisj.gui.MainWindow.MainWindow().
JToolBar micropolisj.gui.MainWindow.makeToolbar () private
Definition at line 1017 of file MainWindow.java.
References micropolisj.engine.MicropolisTool.AIRPORT, micropolisj.engine.MicropolisTool.BULLDOZER, micropolisj.engine.MicropolisTool.COMMERCIAL, micropolisj.engine.MicropolisTool.FIRE, micropolisj.engine.MicropolisTool.INDUSTRIAL, micropolisj.gui.MainWindow.makeToolBtn(), micropolisj.engine.MicropolisTool.NUCLEAR, micropolisj.engine.MicropolisTool.PARK, micropolisj.engine.MicropolisTool.POLICE, micropolisj.engine.MicropolisTool.POWERPLANT, micropolisj.engine.MicropolisTool.QUERY, micropolisj.engine.MicropolisTool.RAIL, micropolisj.engine.MicropolisTool.RESIDENTIAL, micropolisj.engine.MicropolisTool.ROADS, micropolisj.engine.MicropolisTool.ROCKET, micropolisj.engine.MicropolisTool.SEAPORT, micropolisj.engine.MicropolisTool.STADIUM, micropolisj.engine.MicropolisTool.TEMPEL, micropolisj.gui.MainWindow.toolBtns, micropolisj.engine.MicropolisTool.UNIVERSITY, and micropolisj.engine.MicropolisTool.WIRE.
Referenced by micropolisj.gui.MainWindow.MainWindow().
JToggleButton micropolisj.gui.MainWindow.makeToolBtn (final MicropolisTool tool) private
Definition at line 992 of file MainWindow.java.
References micropolisj.gui.MainWindow.selectTool(), and micropolisj.gui.MainWindow.toolBtns.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
void micropolisj.gui.MainWindow.onAboutClicked () private
Definition at line 1728 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onAutoBudgetClicked () private
Definition at line 834 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), and micropolisj.engine.Micropolis.toggleAutoBudget().
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onAutoBulldozeClicked () private
Definition at line 839 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), and micropolisj.engine.Micropolis.toggleAutoBulldoze().
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onCountdown (int count)
Implements micropolisj.engine.TempelListener.
Definition at line 1777 of file MainWindow.java.
void micropolisj.gui.MainWindow.onDifficultyClicked (int newDifficulty) private
Definition at line 1527 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), and micropolisj.engine.Micropolis.setGameLevel().
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onDisastersClicked () private
Definition at line 844 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), and micropolisj.engine.Micropolis.toggleDisasters().
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onEnd ()
Implements micropolisj.engine.TempelListener.
Definition at line 1783 of file MainWindow.java.
void micropolisj.gui.MainWindow.onEscapePressed () private
Definition at line 1264 of file MainWindow.java.
References micropolisj.gui.MicropolisDrawingArea.setToolCursor(), and micropolisj.gui.MicropolisDrawingArea.setToolPreview().
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.onInvokeDisasterClicked (Disaster disaster) private
Definition at line 1540 of file MainWindow.java.
References micropolisj.gui.MessagesPane.appendCityMessage(), micropolisj.gui.MainWindow.getEngine(), micropolisj.engine.Micropolis.makeEarthquake(), micropolisj.engine.Micropolis.makeFire(), micropolisj.engine.Micropolis.makeFlood(), micropolisj.engine.Micropolis.makeMonster(), micropolisj.engine.Micropolis.makeTornado(), and micropolisj.engine.MicropolisMessage.NO_NUCLEAR_PLANTS.
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onLaunchTranslationToolClicked () private
Definition at line 1720 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onLoadGameClicked ()
Definition at line 939 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), micropolisj.network.ServerMicropolis.getPlayerInfos(), micropolisj.network.ServerMicropolis.getServer(), micropolisj.engine.Micropolis.load(), micropolisj.gui.MainWindow.setEngine(), micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.stopTimer().
Referenced by micropolisj.gui.EndGamePane.loadGame(), micropolisj.gui.SplashScreen.loadGame(), and micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onMouseWheelMoved (MouseWheelEvent evt) private
Definition at line 1188 of file MainWindow.java.
References micropolisj.gui.MainWindow.doZoom().
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.onNewCityClicked () private
Definition at line 1133 of file MainWindow.java.
References micropolisj.gui.MainWindow.doNewCity().
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onPriorityClicked (Speed newSpeed) private
Definition at line 1531 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), micropolisj.engine.Micropolis.setSpeed(), micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.stopTimer().
Referenced by micropolisj.gui.MainWindow.makeMenu().
boolean micropolisj.gui.MainWindow.onSaveCityAsClicked () private
Definition at line 906 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), micropolisj.engine.Micropolis.save(), micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.stopTimer().
Referenced by micropolisj.gui.MainWindow.makeMenu(), and micropolisj.gui.MainWindow.onSaveCityClicked().
boolean micropolisj.gui.MainWindow.onSaveCityClicked () private
Definition at line 886 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), micropolisj.gui.MainWindow.onSaveCityAsClicked(), and micropolisj.engine.Micropolis.save().
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onSoundClicked () private
Definition at line 852 of file MainWindow.java.
References micropolisj.util.MP3.close(), micropolisj.util.MP3.play(), and micropolisj.gui.MainWindow.reloadOptions().
Referenced by micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.onToolDown (MouseEvent ev) private
Definition at line 1204 of file MainWindow.java.
References micropolisj.engine.MicropolisTool.beginStroke(), micropolisj.gui.MicropolisDrawingArea.getCityLocation(), micropolisj.engine.MicropolisTool.QUERY, micropolisj.engine.CityLocation.x, and micropolisj.engine.CityLocation.y.
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.onToolDrag (MouseEvent ev) private
Definition at line 1286 of file MainWindow.java.
References micropolisj.engine.ToolStroke.dragTo(), micropolisj.gui.MicropolisDrawingArea.getCityLocation(), micropolisj.engine.MicropolisTool.QUERY, micropolisj.engine.MicropolisTool.ROCKET, micropolisj.engine.CityLocation.x, and micropolisj.engine.CityLocation.y.
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.onToolExited (MouseEvent ev) private
Definition at line 1333 of file MainWindow.java.
References micropolisj.gui.MicropolisDrawingArea.setToolCursor().
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.onToolHover (MouseEvent ev) private
Definition at line 1313 of file MainWindow.java.
References micropolisj.gui.MicropolisDrawingArea.getCityLocation(), micropolisj.engine.MicropolisTool.getHeight(), micropolisj.engine.MicropolisTool.getWidth(), micropolisj.engine.MicropolisTool.QUERY, micropolisj.gui.MicropolisDrawingArea.setToolCursor(), micropolisj.engine.CityLocation.x, and micropolisj.engine.CityLocation.y.
Referenced by micropolisj.gui.MainWindow.MainWindow(), and micropolisj.gui.MainWindow.onToolUp().
void micropolisj.gui.MainWindow.onToolUp (MouseEvent ev) private
Definition at line 1234 of file MainWindow.java.
References micropolisj.engine.ToolStroke.apply(), micropolisj.engine.ToolStroke.getLocation(), micropolisj.gui.MainWindow.onToolHover(), micropolisj.engine.MicropolisTool.ROCKET, micropolisj.gui.MicropolisDrawingArea.setToolPreview(), micropolisj.gui.MainWindow.showBudgetWindow(), and micropolisj.gui.MainWindow.showToolResult().
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.onWindowClosed (WindowEvent ev) private
Definition at line 1521 of file MainWindow.java.
References micropolisj.gui.MainWindow.stopTimer().
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.optionsChanged ()
Fired whenever autoBulldoze, autoBudget, noDisasters, or simSpeed change.
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 1587 of file MainWindow.java.
References micropolisj.gui.MainWindow.reloadOptions().
void micropolisj.gui.MainWindow.reloadFunds () private
Definition at line 1568 of file MainWindow.java.
References micropolisj.gui.MainWindow.formatFunds(), and micropolisj.gui.MainWindow.getEngine().
Referenced by micropolisj.gui.MainWindow.fundsChanged(), micropolisj.gui.MainWindow.MainWindow(), and micropolisj.gui.MainWindow.setEngine().
void micropolisj.gui.MainWindow.reloadOptions () private
Definition at line 1591 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), micropolisj.engine.GameLevel.MAX_LEVEL, and micropolisj.engine.GameLevel.MIN_LEVEL.
Referenced by micropolisj.gui.MainWindow.MainWindow(), micropolisj.gui.MainWindow.onSoundClicked(), micropolisj.gui.MainWindow.optionsChanged(), and micropolisj.gui.MainWindow.setEngine().
void micropolisj.gui.MainWindow.selectTool (MicropolisTool newTool) private
Definition at line 1114 of file MainWindow.java.
References micropolisj.gui.MainWindow.formatFunds(), micropolisj.engine.MicropolisTool.getToolCost(), and micropolisj.gui.MainWindow.toolBtns.
Referenced by micropolisj.gui.MainWindow.makeToolBtn().
void micropolisj.gui.MainWindow.setEngine (Micropolis newEngine)
Definition at line 381 of file MainWindow.java.
References micropolisj.engine.Micropolis.addEarthquakeListener(), micropolisj.engine.Micropolis.addListener(), micropolisj.gui.MainWindow.reloadFunds(), micropolisj.gui.MainWindow.reloadOptions(), micropolisj.engine.Micropolis.removeEarthquakeListener(), micropolisj.engine.Micropolis.removeListener(), micropolisj.gui.DemandIndicator.setEngine(), micropolisj.gui.OverlayMapView.setEngine(), micropolisj.gui.EvaluationPane.setEngine(), micropolisj.gui.GraphsPane.setEngine(), micropolisj.gui.MicropolisDrawingArea.setEngine(), micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.stopTimer().
Referenced by micropolisj.gui.MainWindow.onLoadGameClicked().
void micropolisj.gui.MainWindow.setMapLegend (MapState state) private
Definition at line 1705 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.setMapState().
void micropolisj.gui.MainWindow.setMapState (MapState state) private
Definition at line 1698 of file MainWindow.java.
References micropolisj.gui.OverlayMapView.getMapState(), micropolisj.gui.MainWindow.setMapLegend(), and micropolisj.gui.OverlayMapView.setMapState().
Referenced by micropolisj.gui.MainWindow.MainWindow(), and micropolisj.gui.MainWindow.makeMapStateMenuItem().
void micropolisj.gui.MainWindow.setupKeys (JMenu menu, String prefix) private
Definition at line 498 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.MainWindow(), micropolisj.gui.MainWindow.makeMapStateMenuItem(), and micropolisj.gui.MainWindow.makeMenu().
void micropolisj.gui.MainWindow.setupKeys (JMenuItem menuItem, String prefix) private
Definition at line 505 of file MainWindow.java.
void micropolisj.gui.MainWindow.showAutoBudget () private
Definition at line 1661 of file MainWindow.java.
References micropolisj.gui.MainWindow.showBudgetWindow().
Referenced by micropolisj.gui.MainWindow.startTimer().
void micropolisj.gui.MainWindow.showBudgetWindow (boolean isEndOfYear) private
Definition at line 1670 of file MainWindow.java.
References micropolisj.gui.MainWindow.getEngine(), micropolisj.gui.MainWindow.startTimer(), and micropolisj.gui.MainWindow.stopTimer().
Referenced by micropolisj.gui.MainWindow.onToolUp(), and micropolisj.gui.MainWindow.showAutoBudget().
void micropolisj.gui.MainWindow.showErrorMessage (Throwable e) private
Definition at line 1440 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.MainWindow().
void micropolisj.gui.MainWindow.showToolResult (CityLocation loc, ToolResult result)
Definition at line 1337 of file MainWindow.java.
References micropolisj.gui.MessagesPane.appendCityMessage(), micropolisj.engine.Sound.BUILD, micropolisj.engine.Sound.BULLDOZE, micropolisj.engine.MicropolisMessage.BULLDOZE_FIRST, micropolisj.engine.MicropolisTool.BULLDOZER, micropolisj.gui.MainWindow.citySound(), micropolisj.engine.MicropolisMessage.INSUFFICIENT_FUNDS, micropolisj.engine.Sound.SORRY, and micropolisj.engine.Sound.UHUH.
Referenced by micropolisj.gui.MainWindow.onToolUp().
void micropolisj.gui.MainWindow.startTimer () private
Definition at line 1382 of file MainWindow.java.
References micropolisj.engine.Micropolis.animate(), micropolisj.engine.Speed.animationDelay, micropolisj.engine.Micropolis.autoBudget, micropolisj.gui.MainWindow.getEngine(), micropolisj.engine.Micropolis.isBudgetTime(), micropolisj.engine.Speed.PAUSED, micropolisj.gui.MainWindow.showAutoBudget(), micropolisj.engine.Micropolis.simSpeed, micropolisj.engine.Speed.simStepsPerUpdate, micropolisj.gui.MainWindow.stopTimer(), and micropolisj.gui.MainWindow.updateDateLabel().
Referenced by micropolisj.gui.MainWindow.doNewCity(), micropolisj.gui.MainWindow.earthquakeStarted(), micropolisj.gui.MainWindow.MainWindow(), micropolisj.gui.MainWindow.onLoadGameClicked(), micropolisj.gui.MainWindow.onPriorityClicked(), micropolisj.gui.MainWindow.onSaveCityAsClicked(), micropolisj.gui.MainWindow.setEngine(), and micropolisj.gui.MainWindow.showBudgetWindow().
void micropolisj.gui.MainWindow.stopTimer () private
Definition at line 1504 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.doNewCity(), micropolisj.gui.MainWindow.earthquakeStarted(), micropolisj.gui.MainWindow.onLoadGameClicked(), micropolisj.gui.MainWindow.onPriorityClicked(), micropolisj.gui.MainWindow.onSaveCityAsClicked(), micropolisj.gui.MainWindow.onWindowClosed(), micropolisj.gui.MainWindow.setEngine(), micropolisj.gui.MainWindow.showBudgetWindow(), and micropolisj.gui.MainWindow.startTimer().
void micropolisj.gui.MainWindow.updateDateLabel () private
Definition at line 1372 of file MainWindow.java.
References micropolisj.engine.Micropolis.cityTime, micropolisj.gui.MainWindow.formatGameDate(), micropolisj.gui.MainWindow.getEngine(), and micropolisj.engine.Micropolis.getPlayerID().
Referenced by micropolisj.gui.MainWindow.startTimer().
Member Data Documentation
final int micropolisj.gui.MainWindow.SCROLLING_SPEED = 100 static private
Definition at line 125 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.dispatchKeyEvent().
Map<MicropolisTool, JToggleButton> micropolisj.gui.MainWindow.toolBtns
Definition at line 111 of file MainWindow.java.
Referenced by micropolisj.gui.MainWindow.dispatchKeyEvent(), micropolisj.gui.MainWindow.MainWindow(), micropolisj.gui.MainWindow.makeToolbar(), micropolisj.gui.MainWindow.makeToolBtn(), micropolisj.gui.NewCityDialog.NewCityDialog(), and micropolisj.gui.MainWindow.selectTool().
The documentation for this class was generated from the following file:
src/micropolisj/gui/MainWindow.java