Methapolis: micropolisj.gui.EvaluationPane Class Reference
micropolisj.gui.EvaluationPane Class Reference
Public Member Functions
EvaluationPane (Micropolis _engine)
void setEngine (Micropolis newEngine)
void cityMessage (MicropolisMessage message, CityLocation loc)
void citySound (Sound sound, CityLocation loc)
void censusChanged ()
void demandChanged ()
void fundsChanged ()
void optionsChanged ()
void evaluationChanged ()
Private Member Functions
void onDismissClicked ()
JComponent makePublicOpinionPane ()
JComponent makeStatisticsPane ()
void loadEvaluation ()
Detailed Description
Definition at line 20 of file EvaluationPane.java.
Constructor & Destructor Documentation
micropolisj.gui.EvaluationPane.EvaluationPane (Micropolis _engine)
Definition at line 38 of file EvaluationPane.java.
References micropolisj.gui.EvaluationPane.makePublicOpinionPane(), micropolisj.gui.EvaluationPane.makeStatisticsPane(), micropolisj.gui.EvaluationPane.onDismissClicked(), and micropolisj.gui.EvaluationPane.setEngine().
Member Function Documentation
void micropolisj.gui.EvaluationPane.censusChanged ()
Fired whenever the "census" is taken, and the various historical counters have been updated. (Once a month in game.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 241 of file EvaluationPane.java.
void micropolisj.gui.EvaluationPane.cityMessage (MicropolisMessage message, CityLocation loc)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 235 of file EvaluationPane.java.
void micropolisj.gui.EvaluationPane.citySound (Sound sound, CityLocation loc)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 238 of file EvaluationPane.java.
void micropolisj.gui.EvaluationPane.demandChanged ()
Fired whenever playerInfo.resValve, playerInfo.comValve, or playerInfo.indValve changes. (Twice a month in game.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 244 of file EvaluationPane.java.
void micropolisj.gui.EvaluationPane.evaluationChanged ()
Fired whenever the city playerInfo.evaluation is recalculated. (Once a year.)
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 254 of file EvaluationPane.java.
References micropolisj.gui.EvaluationPane.loadEvaluation().
void micropolisj.gui.EvaluationPane.fundsChanged ()
Fired whenever the mayor's money changes.
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 247 of file EvaluationPane.java.
void micropolisj.gui.EvaluationPane.loadEvaluation () private
Definition at line 258 of file EvaluationPane.java.
References micropolisj.engine.Micropolis.gameLevel, and micropolisj.engine.Micropolis.getPlayerInfo().
Referenced by micropolisj.gui.EvaluationPane.evaluationChanged(), and micropolisj.gui.EvaluationPane.setEngine().
JComponent micropolisj.gui.EvaluationPane.makePublicOpinionPane () private
Definition at line 75 of file EvaluationPane.java.
Referenced by micropolisj.gui.EvaluationPane.EvaluationPane().
JComponent micropolisj.gui.EvaluationPane.makeStatisticsPane () private
Definition at line 150 of file EvaluationPane.java.
Referenced by micropolisj.gui.EvaluationPane.EvaluationPane().
void micropolisj.gui.EvaluationPane.onDismissClicked () private
Definition at line 71 of file EvaluationPane.java.
Referenced by micropolisj.gui.EvaluationPane.EvaluationPane().
void micropolisj.gui.EvaluationPane.optionsChanged ()
Fired whenever autoBulldoze, autoBudget, noDisasters, or simSpeed change.
Implements micropolisj.engine.Micropolis.Listener.
Definition at line 250 of file EvaluationPane.java.
void micropolisj.gui.EvaluationPane.setEngine (Micropolis newEngine)
Definition at line 60 of file EvaluationPane.java.
References micropolisj.engine.Micropolis.addListener(), micropolisj.gui.EvaluationPane.loadEvaluation(), and micropolisj.engine.Micropolis.removeListener().
Referenced by micropolisj.gui.EvaluationPane.EvaluationPane(), and micropolisj.gui.MainWindow.setEngine().
The documentation for this class was generated from the following file:
src/micropolisj/gui/EvaluationPane.java