Methapolis: micropolisj.gui.EndGamePane Class Reference
micropolisj.gui.EndGamePane Class Reference
Public Member Functions
EndGamePane (MainWindow mainWindow)
Private Member Functions
void startJoinGameScreen ()
void startNewGame ()
void startNewServer ()
void loadGame ()
void continueGame ()
void closeThis ()
Detailed Description
Definition at line 15 of file EndGamePane.java.
Constructor & Destructor Documentation
micropolisj.gui.EndGamePane.EndGamePane (MainWindow mainWindow)
Definition at line 19 of file EndGamePane.java.
References micropolisj.gui.EndGamePane.continueGame(), micropolisj.gui.EndGamePane.loadGame(), micropolisj.gui.EndGamePane.startJoinGameScreen(), micropolisj.gui.EndGamePane.startNewGame(), and micropolisj.gui.EndGamePane.startNewServer().
Member Function Documentation
void micropolisj.gui.EndGamePane.closeThis () private
Definition at line 126 of file EndGamePane.java.
Referenced by micropolisj.gui.EndGamePane.continueGame(), micropolisj.gui.EndGamePane.loadGame(), micropolisj.gui.EndGamePane.startJoinGameScreen(), micropolisj.gui.EndGamePane.startNewGame(), and micropolisj.gui.EndGamePane.startNewServer().
void micropolisj.gui.EndGamePane.continueGame () private
Definition at line 122 of file EndGamePane.java.
References micropolisj.gui.EndGamePane.closeThis().
Referenced by micropolisj.gui.EndGamePane.EndGamePane().
void micropolisj.gui.EndGamePane.loadGame () private
Definition at line 111 of file EndGamePane.java.
References micropolisj.gui.EndGamePane.closeThis(), and micropolisj.gui.MainWindow.onLoadGameClicked().
Referenced by micropolisj.gui.EndGamePane.EndGamePane().
void micropolisj.gui.EndGamePane.startJoinGameScreen () private
Definition at line 82 of file EndGamePane.java.
References micropolisj.gui.EndGamePane.closeThis().
Referenced by micropolisj.gui.EndGamePane.EndGamePane().
void micropolisj.gui.EndGamePane.startNewGame () private
Definition at line 89 of file EndGamePane.java.
References micropolisj.gui.EndGamePane.closeThis(), and micropolisj.gui.MainWindow.doNewCity().
Referenced by micropolisj.gui.EndGamePane.EndGamePane().
void micropolisj.gui.EndGamePane.startNewServer () private
Definition at line 100 of file EndGamePane.java.
References micropolisj.gui.EndGamePane.closeThis(), and micropolisj.gui.MainWindow.doNewCity().
Referenced by micropolisj.gui.EndGamePane.EndGamePane().
The documentation for this class was generated from the following file:
src/micropolisj/gui/EndGamePane.java