Methapolis: micropolisj.util.Utilities Class Reference
micropolisj.util.Utilities Class Reference
Static Public Member Functions
static short codePlayerID (int tileValue, int playerID)
static int getPlayerID (char encodedTile)
static int getPlayerID (int encodedTile)
static int getPlayerID (short encodedTile)
static Rectangle moveRectangle (Rectangle rec, int dx, int dy)
Detailed Description
Definition at line 7 of file Utilities.java.
Member Function Documentation
static short micropolisj.util.Utilities.codePlayerID (int tileValue, int playerID) static
Definition at line 12 of file Utilities.java.
References micropolisj.engine.TileConstants.LOMASK.
Referenced by micropolisj.engine.ToolPreview.setTile(), and micropolisj.engine.Micropolis.setTile().
static int micropolisj.util.Utilities.getPlayerID (char encodedTile) static
Definition at line 18 of file Utilities.java.
Referenced by micropolisj.util.Utilities.getPlayerID().
static int micropolisj.util.Utilities.getPlayerID (int encodedTile) static
Definition at line 22 of file Utilities.java.
References micropolisj.util.Utilities.getPlayerID().
static int micropolisj.util.Utilities.getPlayerID (short encodedTile) static
Definition at line 26 of file Utilities.java.
References micropolisj.engine.TileConstants.PWRBIT.
static Rectangle micropolisj.util.Utilities.moveRectangle (Rectangle rec, int dx, int dy) static
Definition at line 33 of file Utilities.java.
Referenced by micropolisj.gui.MainWindow.dispatchKeyEvent().
The documentation for this class was generated from the following file:
src/micropolisj/util/Utilities.java