Methapolis: micropolisj.gui.SplashScreen Class Reference
micropolisj.gui.SplashScreen Class Reference
Classes
class HandlerHost
class HandlerLoad
class HandlerLogin
class HandlerNewGame
Public Member Functions
SplashScreen ()
Protected Member Functions
void paintComponent (Graphics g)
Private Member Functions
void startJoinGameScreen ()
void startNewGame ()
void startNewServer ()
void loadGame ()
void closeThis ()
void removeBackgroundPanels ()
void addBackgroundPanels ()
Detailed Description
Definition at line 21 of file SplashScreen.java.
Constructor & Destructor Documentation
micropolisj.gui.SplashScreen.SplashScreen ()
Definition at line 37 of file SplashScreen.java.
Member Function Documentation
void micropolisj.gui.SplashScreen.addBackgroundPanels () private
Definition at line 277 of file SplashScreen.java.
Referenced by micropolisj.gui.SplashScreen.HandlerNewGame.mouseEntered(), micropolisj.gui.SplashScreen.HandlerHost.mouseEntered(), micropolisj.gui.SplashScreen.HandlerLogin.mouseEntered(), micropolisj.gui.SplashScreen.HandlerLoad.mouseEntered(), micropolisj.gui.SplashScreen.HandlerNewGame.mouseExited(), micropolisj.gui.SplashScreen.HandlerHost.mouseExited(), micropolisj.gui.SplashScreen.HandlerLogin.mouseExited(), and micropolisj.gui.SplashScreen.HandlerLoad.mouseExited().
void micropolisj.gui.SplashScreen.closeThis () private
Definition at line 129 of file SplashScreen.java.
Referenced by micropolisj.gui.SplashScreen.loadGame(), micropolisj.gui.SplashScreen.startJoinGameScreen(), micropolisj.gui.SplashScreen.startNewGame(), and micropolisj.gui.SplashScreen.startNewServer().
void micropolisj.gui.SplashScreen.loadGame () private
Definition at line 120 of file SplashScreen.java.
References micropolisj.gui.SplashScreen.closeThis(), and micropolisj.gui.MainWindow.onLoadGameClicked().
Referenced by micropolisj.gui.SplashScreen.HandlerLoad.mouseClicked().
void micropolisj.gui.SplashScreen.paintComponent (Graphics g) protected
Definition at line 254 of file SplashScreen.java.
void micropolisj.gui.SplashScreen.removeBackgroundPanels () private
Definition at line 269 of file SplashScreen.java.
Referenced by micropolisj.gui.SplashScreen.HandlerNewGame.mouseEntered(), micropolisj.gui.SplashScreen.HandlerHost.mouseEntered(), micropolisj.gui.SplashScreen.HandlerLogin.mouseEntered(), micropolisj.gui.SplashScreen.HandlerLoad.mouseEntered(), micropolisj.gui.SplashScreen.HandlerNewGame.mouseExited(), micropolisj.gui.SplashScreen.HandlerHost.mouseExited(), micropolisj.gui.SplashScreen.HandlerLogin.mouseExited(), and micropolisj.gui.SplashScreen.HandlerLoad.mouseExited().
void micropolisj.gui.SplashScreen.startJoinGameScreen () private
Definition at line 97 of file SplashScreen.java.
References micropolisj.gui.SplashScreen.closeThis().
Referenced by micropolisj.gui.SplashScreen.HandlerLogin.mouseClicked().
void micropolisj.gui.SplashScreen.startNewGame () private
Definition at line 102 of file SplashScreen.java.
References micropolisj.gui.SplashScreen.closeThis(), and micropolisj.gui.MainWindow.doNewCity().
Referenced by micropolisj.gui.SplashScreen.HandlerNewGame.mouseClicked().
void micropolisj.gui.SplashScreen.startNewServer () private
Definition at line 111 of file SplashScreen.java.
References micropolisj.gui.SplashScreen.closeThis(), and micropolisj.gui.MainWindow.doNewCity().
Referenced by micropolisj.gui.SplashScreen.HandlerHost.mouseClicked().
The documentation for this class was generated from the following file:
src/micropolisj/gui/SplashScreen.java