Methapolis: micropolisj.network.RemoteClient Class Reference
micropolisj.network.RemoteClient Class Reference
Public Member Functions
RemoteClient (String ip) throws RemoteException
PlayerInfo getPlayerInfo ()
int getID ()
void sendInput (PlayerInput input)
MapInfo getMap ()
String getIP ()
Private Attributes
transient IMicropolisServer server
String IP
int playerID
Detailed Description
Definition at line 12 of file RemoteClient.java.
Constructor & Destructor Documentation
micropolisj.network.RemoteClient.RemoteClient (String ip) throws RemoteException
Definition at line 20 of file RemoteClient.java.
References micropolisj.network.IMicropolisServer.getNewID(), micropolisj.network.RemoteClient.IP, micropolisj.network.NetworkServer.NAMING_BIND, micropolisj.network.RemoteClient.playerID, and micropolisj.network.RemoteClient.server.
Member Function Documentation
int micropolisj.network.RemoteClient.getID ()
Definition at line 49 of file RemoteClient.java.
References micropolisj.network.RemoteClient.playerID.
Referenced by micropolisj.network.ClientMicropolis.getPlayerID().
String micropolisj.network.RemoteClient.getIP ()
Definition at line 72 of file RemoteClient.java.
References micropolisj.network.RemoteClient.IP.
Referenced by micropolisj.network.ClientMicropolis.getPlayerIP().
MapInfo micropolisj.network.RemoteClient.getMap ()
Definition at line 62 of file RemoteClient.java.
References micropolisj.network.IMicropolisServer.getLatestMap(), and micropolisj.network.RemoteClient.server.
Referenced by micropolisj.network.ClientMicropolis.animate().
PlayerInfo micropolisj.network.RemoteClient.getPlayerInfo ()
Definition at line 39 of file RemoteClient.java.
References micropolisj.network.IMicropolisServer.getPlayerInfo(), micropolisj.network.RemoteClient.playerID, and micropolisj.network.RemoteClient.server.
Referenced by micropolisj.network.ClientMicropolis.animate().
void micropolisj.network.RemoteClient.sendInput (PlayerInput input)
Definition at line 53 of file RemoteClient.java.
References micropolisj.network.RemoteClient.playerID, micropolisj.network.RemoteClient.server, and micropolisj.network.IMicropolisServer.storeInput().
Referenced by micropolisj.network.ClientMicropolis.setBudgetNumbers(), and micropolisj.network.ClientMicropolis.toolUsed().
Member Data Documentation
String micropolisj.network.RemoteClient.IP private
Definition at line 16 of file RemoteClient.java.
Referenced by micropolisj.network.RemoteClient.getIP(), and micropolisj.network.RemoteClient.RemoteClient().
int micropolisj.network.RemoteClient.playerID private
Definition at line 18 of file RemoteClient.java.
Referenced by micropolisj.network.RemoteClient.getID(), micropolisj.network.RemoteClient.getPlayerInfo(), micropolisj.network.RemoteClient.RemoteClient(), and micropolisj.network.RemoteClient.sendInput().
transient IMicropolisServer micropolisj.network.RemoteClient.server private
Definition at line 14 of file RemoteClient.java.
Referenced by micropolisj.network.RemoteClient.getMap(), micropolisj.network.RemoteClient.getPlayerInfo(), micropolisj.network.RemoteClient.RemoteClient(), and micropolisj.network.RemoteClient.sendInput().
The documentation for this class was generated from the following file:
src/micropolisj/network/RemoteClient.java