Methapolis: micropolisj.engine.ToolStroke Class Reference
micropolisj.engine.ToolStroke Class Reference
Public Member Functions
ToolStroke (Micropolis city, MicropolisTool tool, int xpos, int ypos)
void setCity (Micropolis engine)
final ToolPreview getPreview ()
final ToolResult apply ()
void dragTo (int xdest, int ydest)
CityRect getBounds ()
CityLocation getLocation ()
Protected Member Functions
void applyArea (ToolEffectIfc eff)
void fixZone (int xpos, int ypos)
void fixZone (ToolEffectIfc eff)
Private Member Functions
void fixSingle (ToolEffectIfc eff)
Detailed Description
Definition at line 19 of file ToolStroke.java.
Constructor & Destructor Documentation
micropolisj.engine.ToolStroke.ToolStroke (Micropolis city, MicropolisTool tool, int xpos, int ypos)
Definition at line 30 of file ToolStroke.java.
References micropolisj.engine.Micropolis.getPlayerID().
Member Function Documentation
final ToolResult micropolisj.engine.ToolStroke.apply ()
Definition at line 56 of file ToolStroke.java.
References micropolisj.engine.ToolStroke.applyArea().
Referenced by micropolisj.network.ServerMicropolis.animate(), and micropolisj.gui.MainWindow.onToolUp().
void micropolisj.engine.ToolStroke.applyArea (ToolEffectIfc eff) protected
Definition at line 62 of file ToolStroke.java.
References micropolisj.engine.ToolStroke.getBounds(), micropolisj.engine.MicropolisTool.getHeight(), micropolisj.engine.MicropolisTool.getWidth(), micropolisj.engine.CityRect.height, micropolisj.engine.CityRect.width, micropolisj.engine.CityRect.x, and micropolisj.engine.CityRect.y.
Referenced by micropolisj.engine.ToolStroke.apply(), and micropolisj.engine.ToolStroke.getPreview().
void micropolisj.engine.ToolStroke.dragTo (int xdest, int ydest)
Definition at line 140 of file ToolStroke.java.
Referenced by micropolisj.gui.MainWindow.onToolDrag().
void micropolisj.engine.ToolStroke.fixSingle (ToolEffectIfc eff) private
Definition at line 290 of file ToolStroke.java.
References micropolisj.engine.ToolEffectIfc.getTile(), and micropolisj.engine.ToolEffectIfc.setTile().
Referenced by micropolisj.engine.ToolStroke.fixZone().
void micropolisj.engine.ToolStroke.fixZone (int xpos, int ypos) protected
Definition at line 274 of file ToolStroke.java.
void micropolisj.engine.ToolStroke.fixZone (ToolEffectIfc eff) protected
Definition at line 280 of file ToolStroke.java.
References micropolisj.engine.ToolStroke.fixSingle().
CityRect micropolisj.engine.ToolStroke.getBounds ()
Definition at line 145 of file ToolStroke.java.
References micropolisj.engine.MicropolisTool.getHeight(), micropolisj.engine.MicropolisTool.getWidth(), micropolisj.engine.CityRect.height, micropolisj.engine.CityRect.width, micropolisj.engine.CityRect.x, and micropolisj.engine.CityRect.y.
Referenced by micropolisj.engine.ToolStroke.applyArea().
CityLocation micropolisj.engine.ToolStroke.getLocation ()
Definition at line 173 of file ToolStroke.java.
Referenced by micropolisj.gui.MainWindow.onToolUp().
final ToolPreview micropolisj.engine.ToolStroke.getPreview ()
Definition at line 45 of file ToolStroke.java.
References micropolisj.engine.ToolStroke.applyArea().
void micropolisj.engine.ToolStroke.setCity (Micropolis engine)
Definition at line 41 of file ToolStroke.java.
Referenced by micropolisj.network.ServerMicropolis.animate().
The documentation for this class was generated from the following file:
src/micropolisj/engine/ToolStroke.java