Methapolis: micropolisj.util.MP3 Class Reference
micropolisj.util.MP3 Class Reference
Classes
class LoopListener
class NonLoopListener
Public Member Functions
MP3 (String filename)
MP3 (URL url)
MP3 (URL url, boolean loop)
MP3 (String filename, boolean loop)
void close ()
AdvancedPlayer createPlayer ()
void play ()
Private Attributes
String filename
AdvancedPlayer player
boolean loop
volatile Thread thread
Detailed Description
Definition at line 31 of file MP3.java.
Constructor & Destructor Documentation
micropolisj.util.MP3.MP3 (String filename)
Definition at line 38 of file MP3.java.
References micropolisj.util.MP3.filename.
micropolisj.util.MP3.MP3 (URL url)
Definition at line 42 of file MP3.java.
micropolisj.util.MP3.MP3 (URL url, boolean loop)
Definition at line 46 of file MP3.java.
References micropolisj.util.MP3.loop.
micropolisj.util.MP3.MP3 (String filename, boolean loop)
Definition at line 51 of file MP3.java.
References micropolisj.util.MP3.filename, micropolisj.util.MP3.loop, micropolisj.util.MP3.player, and micropolisj.util.MP3.thread.
Member Function Documentation
void micropolisj.util.MP3.close ()
Definition at line 60 of file MP3.java.
References micropolisj.util.MP3.player, and micropolisj.util.MP3.thread.
Referenced by micropolisj.util.MP3.createPlayer(), and micropolisj.gui.MainWindow.onSoundClicked().
AdvancedPlayer micropolisj.util.MP3.createPlayer ()
Definition at line 71 of file MP3.java.
References micropolisj.util.MP3.close(), micropolisj.util.MP3.filename, and micropolisj.util.MP3.loop.
Referenced by micropolisj.util.MP3.play().
void micropolisj.util.MP3.play ()
Definition at line 93 of file MP3.java.
References micropolisj.util.MP3.createPlayer(), micropolisj.util.MP3.player, and micropolisj.util.MP3.thread.
Referenced by micropolisj.engine.SpaceshipSprite.moveImpl(), micropolisj.gui.MainWindow.onSoundClicked(), and micropolisj.util.MP3.LoopListener.playbackFinished().
Member Data Documentation
String micropolisj.util.MP3.filename private
Definition at line 32 of file MP3.java.
Referenced by micropolisj.util.MP3.createPlayer(), and micropolisj.util.MP3.MP3().
boolean micropolisj.util.MP3.loop private
Definition at line 34 of file MP3.java.
Referenced by micropolisj.util.MP3.createPlayer(), and micropolisj.util.MP3.MP3().
AdvancedPlayer micropolisj.util.MP3.player private
Definition at line 33 of file MP3.java.
Referenced by micropolisj.util.MP3.close(), micropolisj.util.MP3.MP3(), and micropolisj.util.MP3.play().
volatile Thread micropolisj.util.MP3.thread private
Definition at line 35 of file MP3.java.
Referenced by micropolisj.util.MP3.close(), micropolisj.util.MP3.MP3(), micropolisj.util.MP3.play(), and micropolisj.util.MP3.NonLoopListener.playbackFinished().
The documentation for this class was generated from the following file:
src/micropolisj/util/MP3.java