Methapolis: micropolisj.network.RemoteDistributor Class Reference
micropolisj.network.RemoteDistributor Class Reference
Public Member Functions
synchronized MapInfo getLatestMap () throws RemoteException
synchronized void setMapInfo (MapInfo mI)
synchronized void storeInput (int playerID, PlayerInput input) throws RemoteException
synchronized Map< PlayerInput,
Integer > getInput ()
void setRemoteClient (RemoteClient client) throws RemoteException
void clearInput ()
byte[] getLevel () throws RemoteException
int getNewID () throws RemoteException
synchronized PlayerInfo getPlayerInfo (int ID) throws RemoteException
Protected Member Functions
RemoteDistributor (ServerMicropolis micropolis) throws RemoteException
Private Attributes
transient ServerMicropolis micropolis
MapInfo mapInfo
Map< PlayerInput, Integer > events
String levelName
Static Private Attributes
static int playerCount = 1
Detailed Description
zentrale zugriffsklasse auf serverseite. bekommt von aussen mapobjekt reingereicht.
Author
nikolaibobenko
Definition at line 19 of file RemoteDistributor.java.
Constructor & Destructor Documentation
micropolisj.network.RemoteDistributor.RemoteDistributor (ServerMicropolis micropolis) throws RemoteException protected
Definition at line 31 of file RemoteDistributor.java.
References micropolisj.network.RemoteDistributor.events, and micropolisj.network.RemoteDistributor.micropolis.
Member Function Documentation
void micropolisj.network.RemoteDistributor.clearInput ()
Definition at line 63 of file RemoteDistributor.java.
References micropolisj.network.RemoteDistributor.events.
Referenced by micropolisj.network.ServerMicropolis.animate().
synchronized Map<PlayerInput, Integer> micropolisj.network.RemoteDistributor.getInput ()
Definition at line 54 of file RemoteDistributor.java.
References micropolisj.network.RemoteDistributor.events.
Referenced by micropolisj.network.ServerMicropolis.animate().
synchronized MapInfo micropolisj.network.RemoteDistributor.getLatestMap () throws RemoteException
Implements micropolisj.network.IMicropolisServer.
Definition at line 40 of file RemoteDistributor.java.
References micropolisj.network.RemoteDistributor.mapInfo.
byte [] micropolisj.network.RemoteDistributor.getLevel () throws RemoteException
Implements micropolisj.network.IMicropolisServer.
Definition at line 68 of file RemoteDistributor.java.
int micropolisj.network.RemoteDistributor.getNewID () throws RemoteException
Implements micropolisj.network.IMicropolisServer.
Definition at line 76 of file RemoteDistributor.java.
References micropolisj.network.ServerMicropolis.addNewPlayer(), micropolisj.network.RemoteDistributor.micropolis, and micropolisj.network.RemoteDistributor.playerCount.
synchronized PlayerInfo micropolisj.network.RemoteDistributor.getPlayerInfo (int ID) throws RemoteException
Implements micropolisj.network.IMicropolisServer.
Definition at line 84 of file RemoteDistributor.java.
References micropolisj.network.ServerMicropolis.getPlayerInfo(), and micropolisj.network.RemoteDistributor.micropolis.
synchronized void micropolisj.network.RemoteDistributor.setMapInfo (MapInfo mI)
Definition at line 45 of file RemoteDistributor.java.
References micropolisj.network.RemoteDistributor.mapInfo.
Referenced by micropolisj.network.ServerMicropolis.animate().
void micropolisj.network.RemoteDistributor.setRemoteClient (RemoteClient client) throws RemoteException
Implements micropolisj.network.IMicropolisServer.
Definition at line 59 of file RemoteDistributor.java.
synchronized void micropolisj.network.RemoteDistributor.storeInput (int playerID, PlayerInput input) throws RemoteException
Implements micropolisj.network.IMicropolisServer.
Definition at line 50 of file RemoteDistributor.java.
References micropolisj.network.RemoteDistributor.events.
Member Data Documentation
Map<PlayerInput, Integer> micropolisj.network.RemoteDistributor.events private
Definition at line 24 of file RemoteDistributor.java.
Referenced by micropolisj.network.RemoteDistributor.clearInput(), micropolisj.network.RemoteDistributor.getInput(), micropolisj.network.RemoteDistributor.RemoteDistributor(), and micropolisj.network.RemoteDistributor.storeInput().
String micropolisj.network.RemoteDistributor.levelName private
Definition at line 26 of file RemoteDistributor.java.
MapInfo micropolisj.network.RemoteDistributor.mapInfo private
Definition at line 23 of file RemoteDistributor.java.
Referenced by micropolisj.network.RemoteDistributor.getLatestMap(), and micropolisj.network.RemoteDistributor.setMapInfo().
transient ServerMicropolis micropolisj.network.RemoteDistributor.micropolis private
Definition at line 22 of file RemoteDistributor.java.
Referenced by micropolisj.network.RemoteDistributor.getNewID(), micropolisj.network.RemoteDistributor.getPlayerInfo(), and micropolisj.network.RemoteDistributor.RemoteDistributor().
int micropolisj.network.RemoteDistributor.playerCount = 1 static private
Definition at line 28 of file RemoteDistributor.java.
Referenced by micropolisj.network.RemoteDistributor.getNewID().
The documentation for this class was generated from the following file:
src/micropolisj/network/RemoteDistributor.java