Methapolis: micropolisj.engine.CityEval Class Reference
micropolisj.engine.CityEval Class Reference
Public Member Functions
CityEval (Micropolis engine)
void setEngine (Micropolis engine)
Public Attributes
int cityYes
int cityNo
int cityAssValue
int cityScore
int deltaCityScore
int cityPop
int deltaCityPop
int cityClass
CityProblem[] problemOrder = new CityProblem[0]
EnumMap< CityProblem, Integer > problemVotes = new EnumMap<CityProblem, Integer>(CityProblem.class)
EnumMap< CityProblem, Integer > problemTable = new EnumMap<CityProblem, Integer>(CityProblem.class)
Private Attributes
transient Micropolis engine
final Random PRNG
Detailed Description
Contains the code for performing a city evaluation.
Definition at line 21 of file CityEval.java.
Constructor & Destructor Documentation
micropolisj.engine.CityEval.CityEval (Micropolis engine)
Definition at line 25 of file CityEval.java.
References micropolisj.engine.CityEval.PRNG, and micropolisj.engine.CityEval.setEngine().
Member Function Documentation
void micropolisj.engine.CityEval.setEngine (Micropolis engine)
Definition at line 297 of file CityEval.java.
References micropolisj.engine.CityEval.engine.
Referenced by micropolisj.network.ClientMicropolis.applyPlayerInfo(), and micropolisj.engine.CityEval.CityEval().
Member Data Documentation
int micropolisj.engine.CityEval.cityAssValue
City assessment value.
Definition at line 42 of file CityEval.java.
int micropolisj.engine.CityEval.cityClass
Classification of city size. 0==village, 1==town, etc.
Definition at line 57 of file CityEval.java.
int micropolisj.engine.CityEval.cityNo
Percentage of population "disapproving" the mayor. Derived from cityScore.
Definition at line 39 of file CityEval.java.
int micropolisj.engine.CityEval.cityPop
City population as of current evaluation.
Definition at line 51 of file CityEval.java.
int micropolisj.engine.CityEval.cityScore
Player's score, 0-1000.
Definition at line 45 of file CityEval.java.
int micropolisj.engine.CityEval.cityYes
Percentage of population "approving" the mayor. Derived from cityScore.
Definition at line 33 of file CityEval.java.
int micropolisj.engine.CityEval.deltaCityPop
Change in cityPopulation since last evaluation.
Definition at line 54 of file CityEval.java.
int micropolisj.engine.CityEval.deltaCityScore
Change in cityScore since last evaluation.
Definition at line 48 of file CityEval.java.
transient Micropolis micropolisj.engine.CityEval.engine private
Definition at line 22 of file CityEval.java.
Referenced by micropolisj.engine.CityEval.setEngine().
final Random micropolisj.engine.CityEval.PRNG private
Definition at line 23 of file CityEval.java.
Referenced by micropolisj.engine.CityEval.CityEval().
CityProblem [] micropolisj.engine.CityEval.problemOrder = new CityProblem[0]
City's top 4 (or fewer) problems as reported by citizens.
Definition at line 60 of file CityEval.java.
EnumMap<CityProblem, Integer> micropolisj.engine.CityEval.problemTable = new EnumMap<CityProblem, Integer>(CityProblem.class)
Score for various problems.
Definition at line 69 of file CityEval.java.
EnumMap<CityProblem, Integer> micropolisj.engine.CityEval.problemVotes = new EnumMap<CityProblem, Integer>(CityProblem.class)
Number of votes given for the various problems identified by problemOrder[].
Definition at line 66 of file CityEval.java.
The documentation for this class was generated from the following file:
src/micropolisj/engine/CityEval.java