Methapolis: micropolisj.network.ClientMicropolis Class Reference
micropolisj.network.ClientMicropolis Class Reference
Public Member Functions
ClientMicropolis (String IP) throws RemoteException
void animate ()
void toolUsed (ToolStroke tool)
void setBudgetNumbers (int newTaxRate, double roadPct, double newRoadPct, double newPolicePct, double newFirePct, double newResearchPct)
int getPlayerID ()
String getPlayerIP ()
PlayerInfo getPlayerInfo (int playerID)
Public Member Functions inherited from micropolisj.engine.Micropolis
void spend (int amount, PlayerInfo playerInfo)
void spend (int amount)
Micropolis ()
Micropolis (int width, int height)
List< Sprite > getSprites ()
void fireFundsChanged ()
void addListener (Listener l)
void removeListener (Listener l)
void addEarthquakeListener (EarthquakeListener l)
void removeEarthquakeListener (EarthquakeListener l)
void addMapListener (MapListener l)
void removeMapListener (MapListener l)
void addTempelListener (TempelListener listener)
void notifyCountdown (int countdown)
void notifyEnd ()
int getWidth ()
int getHeight ()
char getTile (int xpos, int ypos)
char getTileRaw (int xpos, int ypos)
boolean isTilePowered (int xpos, int ypos)
void setTile (int xpos, int ypos, char newTile)
void setTile (int xpos, int ypos, char newTile, int playerID)
final boolean testBounds (int xpos, int ypos)
boolean isBudgetTime ()
void calculateCenterMass ()
int getFireStationCoverage (int xpos, int ypos)
int getLandValue (int xpos, int ypos)
int getTrafficDensity (int xpos, int ypos)
CityLocation getLocationOfMaxPollution ()
void addResearchPoints ()
void addResearchPoints (int playerID)
BudgetNumbers generateBudget ()
BudgetNumbers generateBudget (PlayerInfo playerInfo)
void load (File filename) throws IOException
void load (InputStream inStream) throws IOException
void save (File filename) throws IOException
void save (OutputStream outStream) throws IOException
void toggleAutoBudget ()
void toggleAutoBulldoze ()
void toggleDisasters ()
void setSpeed (Speed newSpeed)
Sprite[] allSprites ()
int getCityPopulation ()
int getCityPopulation (int playerID)
void makeEarthquake ()
void makeFire ()
boolean makeMeltdown ()
void makeMonster ()
void makeTornado ()
void makeFlood ()
ZoneStatus queryZoneStatus (int xpos, int ypos)
int getResValve ()
int getComValve ()
int getIndValve ()
void setGameLevel (int newLevel)
void setFunds (int totalFunds)
int getNumberOfPlayers ()
PlayerInfo getPlayerInfo ()
Private Member Functions
void applyMapInfo (MapInfo info)
void fireEvents ()
void applyPlayerInfo (PlayerInfo playerInfo)
Private Attributes
RemoteClient remote
Additional Inherited Members
Public Attributes inherited from micropolisj.engine.Micropolis
int[][] pollutionMem
int[][] crimeMem
int[][] popDensity
int[][] rateOGMem
int[][] fireRate
int[][] policeMapEffect
int[][] researchMapEffect
PlayerInfo playerInfo
Stack< CityLocation > powerPlants = new Stack<CityLocation>()
boolean autoBulldoze = true
boolean autoBudget = false
Speed simSpeed = Speed.NORMAL
boolean noDisasters = true
int gameLevel
int cityTime
MainWindow mainWindow
History history = new History()
ArrayList< FinancialHistory > financialHistory = new ArrayList<FinancialHistory>()
Static Public Attributes inherited from micropolisj.engine.Micropolis
static final int CENSUSRATE = 4
Protected Member Functions inherited from micropolisj.engine.Micropolis
void init (int width, int height)
void fireCensusChanged ()
void fireCityMessage (MicropolisMessage message, CityLocation loc)
void fireDemandChanged ()
void fireEvaluationChanged ()
void fireMapOverlayDataChanged (MapState overlayDataType)
void fireTileChanged (int xpos, int ypos)
void fireWholeMapChanged ()
void mapScan (int x0, int x1)
void takeCensus ()
void takeCensus2 ()
void moveObjects ()
void animateTiles ()
Protected Attributes inherited from micropolisj.engine.Micropolis
char[][] map
List< Sprite > sprites = new ArrayList<Sprite>()
Detailed Description
Definition at line 11 of file ClientMicropolis.java.
Constructor & Destructor Documentation
micropolisj.network.ClientMicropolis.ClientMicropolis (String IP) throws RemoteException
Definition at line 15 of file ClientMicropolis.java.
References micropolisj.network.ClientMicropolis.remote.
Member Function Documentation
void micropolisj.network.ClientMicropolis.animate ()
Reimplemented from micropolisj.engine.Micropolis.
Definition at line 21 of file ClientMicropolis.java.
References micropolisj.engine.Micropolis.animateTiles(), micropolisj.network.ClientMicropolis.applyMapInfo(), micropolisj.network.ClientMicropolis.applyPlayerInfo(), micropolisj.network.ClientMicropolis.fireEvents(), micropolisj.network.RemoteClient.getMap(), micropolisj.network.RemoteClient.getPlayerInfo(), micropolisj.engine.Micropolis.moveObjects(), micropolisj.engine.Micropolis.playerInfo, and micropolisj.network.ClientMicropolis.remote.
void micropolisj.network.ClientMicropolis.applyMapInfo (MapInfo info) private
Definition at line 35 of file ClientMicropolis.java.
References micropolisj.network.MapInfo.cityTime, micropolisj.engine.Micropolis.cityTime, micropolisj.engine.Micropolis.fireTileChanged(), micropolisj.network.MapInfo.map, micropolisj.engine.Micropolis.map, micropolisj.network.MapInfo.sprites, and micropolisj.engine.Micropolis.sprites.
Referenced by micropolisj.network.ClientMicropolis.animate().
void micropolisj.network.ClientMicropolis.applyPlayerInfo (PlayerInfo playerInfo) private
Definition at line 67 of file ClientMicropolis.java.
References micropolisj.engine.PlayerInfo.evaluation, micropolisj.engine.Micropolis.playerInfo, and micropolisj.engine.CityEval.setEngine().
Referenced by micropolisj.network.ClientMicropolis.animate().
void micropolisj.network.ClientMicropolis.fireEvents () private
Definition at line 57 of file ClientMicropolis.java.
References micropolisj.engine.Micropolis.fireCensusChanged(), micropolisj.engine.Micropolis.fireDemandChanged(), micropolisj.engine.Micropolis.fireEvaluationChanged(), and micropolisj.engine.Micropolis.fireFundsChanged().
Referenced by micropolisj.network.ClientMicropolis.animate().
int micropolisj.network.ClientMicropolis.getPlayerID ()
Reimplemented from micropolisj.engine.Micropolis.
Definition at line 86 of file ClientMicropolis.java.
References micropolisj.network.RemoteClient.getID(), and micropolisj.network.ClientMicropolis.remote.
PlayerInfo micropolisj.network.ClientMicropolis.getPlayerInfo (int playerID)
Reimplemented from micropolisj.engine.Micropolis.
Definition at line 95 of file ClientMicropolis.java.
References micropolisj.engine.Micropolis.playerInfo.
String micropolisj.network.ClientMicropolis.getPlayerIP ()
Definition at line 90 of file ClientMicropolis.java.
References micropolisj.network.RemoteClient.getIP(), and micropolisj.network.ClientMicropolis.remote.
void micropolisj.network.ClientMicropolis.setBudgetNumbers (int newTaxRate, double roadPct, double newRoadPct, double newPolicePct, double newFirePct, double newResearchPct)
Reimplemented from micropolisj.engine.Micropolis.
Definition at line 78 of file ClientMicropolis.java.
References micropolisj.network.ClientMicropolis.remote, micropolisj.network.RemoteClient.sendInput(), and micropolisj.network.PlayerInput.setBudgetNumbers().
void micropolisj.network.ClientMicropolis.toolUsed (ToolStroke tool)
Definition at line 72 of file ClientMicropolis.java.
References micropolisj.network.ClientMicropolis.remote, and micropolisj.network.RemoteClient.sendInput().
Member Data Documentation
RemoteClient micropolisj.network.ClientMicropolis.remote private
Definition at line 13 of file ClientMicropolis.java.
Referenced by micropolisj.network.ClientMicropolis.animate(), micropolisj.network.ClientMicropolis.ClientMicropolis(), micropolisj.network.ClientMicropolis.getPlayerID(), micropolisj.network.ClientMicropolis.getPlayerIP(), micropolisj.network.ClientMicropolis.setBudgetNumbers(), and micropolisj.network.ClientMicropolis.toolUsed().
The documentation for this class was generated from the following file:
src/micropolisj/network/ClientMicropolis.java