Methapolis: micropolisj.research.ResearchState Class Reference
micropolisj.research.ResearchState Class Reference
Public Member Functions
int getPoliceResearchState ()
double getPoliceStationRange ()
int getFiremanResearchState ()
double getFireStationRange ()
int getEnvironmentResearchState ()
int getRocketResearchState ()
void setToolBtns (Map< MicropolisTool, JToggleButton > toolBtns)
ResearchData getResearchData ()
ResearchState (Micropolis city)
ResearchState (Micropolis engine, ResearchTree tree)
void showResearchPanel ()
void refreshPanel ()
void actionPerformed (ActionEvent ev)
Static Public Member Functions
static ResearchState createFromResearchData (Micropolis engine, ResearchData data, Map< MicropolisTool, JToggleButton > toolBtns)
Public Attributes
int policeResearch = 0
int firemanResearch = 0
int environmentResearch = 0
int rocketResearch = 0
ResearchTree tree
int researchPoints = 0
Map< MicropolisTool,
JToggleButton > toolBtns
Private Attributes
Micropolis city
Static Private Attributes
static final long serialVersionUID = 1L
static ResearchState instance = null
Detailed Description
Definition at line 27 of file ResearchState.java.
Constructor & Destructor Documentation
micropolisj.research.ResearchState.ResearchState (Micropolis city)
Definition at line 126 of file ResearchState.java.
References micropolisj.research.ResearchState.city.
Referenced by micropolisj.research.ResearchState.createFromResearchData().
micropolisj.research.ResearchState.ResearchState (Micropolis engine, ResearchTree tree)
Definition at line 131 of file ResearchState.java.
References micropolisj.research.ResearchState.actionPerformed(), micropolisj.research.ResearchState.city, micropolisj.research.ResearchState.refreshPanel(), micropolisj.research.ResearchState.researchPoints, and micropolisj.research.ResearchState.tree.
Member Function Documentation
void micropolisj.research.ResearchState.actionPerformed (ActionEvent ev)
Definition at line 291 of file ResearchState.java.
References micropolisj.research.ResearchState.city, micropolisj.research.ResearchNode.getCost(), micropolisj.engine.Micropolis.getPlayerInfo(), micropolisj.research.ResearchState.getResearchData(), micropolisj.research.ResearchNode.makeChanges(), micropolisj.research.ResearchState.refreshPanel(), micropolisj.engine.PlayerInfo.researchData, and micropolisj.research.ResearchState.researchPoints.
Referenced by micropolisj.research.ResearchState.ResearchState().
static ResearchState micropolisj.research.ResearchState.createFromResearchData (Micropolis engine, ResearchData data, Map< MicropolisTool, JToggleButton > toolBtns) static
Definition at line 103 of file ResearchState.java.
References micropolisj.research.ResearchData.environmentResearch, micropolisj.research.ResearchState.environmentResearch, micropolisj.research.ResearchState.firemanResearch, micropolisj.research.ResearchData.fireResearch, micropolisj.research.ResearchData.policeResearch, micropolisj.research.ResearchState.policeResearch, micropolisj.research.ResearchData.researchPoints, micropolisj.research.ResearchState.researchPoints, micropolisj.research.ResearchState.ResearchState(), micropolisj.research.ResearchData.rocketResearch, micropolisj.research.ResearchState.rocketResearch, and micropolisj.research.ResearchState.setToolBtns().
Referenced by micropolisj.gui.CheatWindow.dispatchKeyEvent().
int micropolisj.research.ResearchState.getEnvironmentResearchState ()
Definition at line 54 of file ResearchState.java.
References micropolisj.research.ResearchState.environmentResearch.
int micropolisj.research.ResearchState.getFiremanResearchState ()
Definition at line 44 of file ResearchState.java.
References micropolisj.research.ResearchState.firemanResearch.
double micropolisj.research.ResearchState.getFireStationRange ()
Definition at line 48 of file ResearchState.java.
References micropolisj.research.ResearchState.firemanResearch.
int micropolisj.research.ResearchState.getPoliceResearchState ()
Definition at line 34 of file ResearchState.java.
References micropolisj.research.ResearchState.policeResearch.
double micropolisj.research.ResearchState.getPoliceStationRange ()
Definition at line 38 of file ResearchState.java.
References micropolisj.research.ResearchState.policeResearch.
ResearchData micropolisj.research.ResearchState.getResearchData ()
Definition at line 115 of file ResearchState.java.
References micropolisj.research.ResearchData.environmentResearch, micropolisj.research.ResearchState.environmentResearch, micropolisj.research.ResearchState.firemanResearch, micropolisj.research.ResearchData.fireResearch, micropolisj.research.ResearchData.policeResearch, micropolisj.research.ResearchState.policeResearch, micropolisj.research.ResearchData.researchPoints, micropolisj.research.ResearchState.researchPoints, micropolisj.research.ResearchData.rocketResearch, and micropolisj.research.ResearchState.rocketResearch.
Referenced by micropolisj.research.ResearchState.actionPerformed(), and micropolisj.engine.PlayerInfo.PlayerInfo().
int micropolisj.research.ResearchState.getRocketResearchState ()
Definition at line 60 of file ResearchState.java.
References micropolisj.research.ResearchState.rocketResearch.
void micropolisj.research.ResearchState.refreshPanel ()
Definition at line 264 of file ResearchState.java.
References micropolisj.research.ResearchNode.getCost(), micropolisj.research.ResearchNode.getDesc(), micropolisj.research.ResearchNode.getName(), micropolisj.research.ResearchState.researchPoints, and micropolisj.research.ResearchState.tree.
Referenced by micropolisj.research.ResearchState.actionPerformed(), micropolisj.engine.Micropolis.addResearchPoints(), micropolisj.research.ResearchState.ResearchState(), and micropolisj.research.ResearchState.showResearchPanel().
void micropolisj.research.ResearchState.setToolBtns (Map< MicropolisTool, JToggleButton > toolBtns)
Definition at line 78 of file ResearchState.java.
References micropolisj.research.ResearchState.toolBtns.
Referenced by micropolisj.research.ResearchState.createFromResearchData(), and micropolisj.gui.MainWindow.MainWindow().
void micropolisj.research.ResearchState.showResearchPanel ()
Definition at line 256 of file ResearchState.java.
References micropolisj.research.ResearchState.refreshPanel().
Member Data Documentation
Micropolis micropolisj.research.ResearchState.city private
Definition at line 75 of file ResearchState.java.
Referenced by micropolisj.research.ResearchState.actionPerformed(), and micropolisj.research.ResearchState.ResearchState().
int micropolisj.research.ResearchState.environmentResearch = 0
Definition at line 52 of file ResearchState.java.
Referenced by micropolisj.research.ResearchState.createFromResearchData(), micropolisj.research.ResearchState.getEnvironmentResearchState(), and micropolisj.research.ResearchState.getResearchData().
int micropolisj.research.ResearchState.firemanResearch = 0
Definition at line 42 of file ResearchState.java.
Referenced by micropolisj.research.ResearchState.createFromResearchData(), micropolisj.research.ResearchState.getFiremanResearchState(), micropolisj.research.ResearchState.getFireStationRange(), and micropolisj.research.ResearchState.getResearchData().
ResearchState micropolisj.research.ResearchState.instance = null static private
Definition at line 92 of file ResearchState.java.
int micropolisj.research.ResearchState.policeResearch = 0
Definition at line 32 of file ResearchState.java.
Referenced by micropolisj.research.ResearchState.createFromResearchData(), micropolisj.research.ResearchState.getPoliceResearchState(), micropolisj.research.ResearchState.getPoliceStationRange(), and micropolisj.research.ResearchState.getResearchData().
int micropolisj.research.ResearchState.researchPoints = 0
Definition at line 73 of file ResearchState.java.
Referenced by micropolisj.research.ResearchState.actionPerformed(), micropolisj.engine.Micropolis.addResearchPoints(), micropolisj.research.ResearchState.createFromResearchData(), micropolisj.research.ResearchState.getResearchData(), micropolisj.research.ResearchState.refreshPanel(), and micropolisj.research.ResearchState.ResearchState().
int micropolisj.research.ResearchState.rocketResearch = 0
Definition at line 58 of file ResearchState.java.
Referenced by micropolisj.research.ResearchState.createFromResearchData(), micropolisj.research.ResearchState.getResearchData(), and micropolisj.research.ResearchState.getRocketResearchState().
final long micropolisj.research.ResearchState.serialVersionUID = 1L static private
Definition at line 28 of file ResearchState.java.
Map<MicropolisTool, JToggleButton> micropolisj.research.ResearchState.toolBtns
Definition at line 77 of file ResearchState.java.
Referenced by micropolisj.gui.NewCityDialog.NewCityDialog(), and micropolisj.research.ResearchState.setToolBtns().
ResearchTree micropolisj.research.ResearchState.tree
Definition at line 69 of file ResearchState.java.
Referenced by micropolisj.research.ResearchState.refreshPanel(), and micropolisj.research.ResearchState.ResearchState().
The documentation for this class was generated from the following file:
src/micropolisj/research/ResearchState.java