Methapolis: micropolisj.engine.MicropolisTool Enum Reference
micropolisj.engine.MicropolisTool Enum Reference
Public Member Functions
int getWidth ()
int getHeight ()
ToolStroke beginStroke (Micropolis engine, int xpos, int ypos)
ToolResult apply (Micropolis engine, int xpos, int ypos)
int getToolCost ()
Public Attributes
BULLDOZER = (1, 1)
WIRE = (1, 5)
ROADS = (1, 10)
RAIL = (1, 20)
RESIDENTIAL = (3, 100)
COMMERCIAL = (3, 100)
INDUSTRIAL = (3, 100)
FIRE = (3, 500)
POLICE = (3, 500)
STADIUM = (4, 5000)
PARK = (1, 10)
SEAPORT = (4, 3000)
POWERPLANT = (4, 3000)
NUCLEAR = (4, 5000)
AIRPORT = (6, 10000)
QUERY = (1, 0)
UNIVERSITY = (3, 5000)
ROCKET = (3, 10000)
TEMPEL = (6, 30000)
int size
int cost
Private Member Functions
MicropolisTool (int size, int cost)
Detailed Description
Enumerates the various tools that can be applied to the map by the user. Call the tool's apply() method to actually use the tool on the map.
Definition at line 18 of file MicropolisTool.java.
Constructor & Destructor Documentation
micropolisj.engine.MicropolisTool.MicropolisTool (int size, int cost) private
Definition at line 43 of file MicropolisTool.java.
Member Function Documentation
ToolResult micropolisj.engine.MicropolisTool.apply (Micropolis engine, int xpos, int ypos)
Definition at line 74 of file MicropolisTool.java.
ToolStroke micropolisj.engine.MicropolisTool.beginStroke (Micropolis engine, int xpos, int ypos)
Definition at line 59 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.onToolDown().
int micropolisj.engine.MicropolisTool.getHeight ()
Definition at line 54 of file MicropolisTool.java.
Referenced by micropolisj.engine.ToolStroke.applyArea(), micropolisj.engine.ToolStroke.getBounds(), and micropolisj.gui.MainWindow.onToolHover().
int micropolisj.engine.MicropolisTool.getToolCost ()
This is the cost displayed in the GUI when the tool is selected. It does not necessarily reflect the cost charged when a tool is applied, as extra may be charged for clearing land or building over or through water.
Definition at line 85 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.selectTool().
int micropolisj.engine.MicropolisTool.getWidth ()
Definition at line 49 of file MicropolisTool.java.
Referenced by micropolisj.engine.ToolStroke.applyArea(), micropolisj.engine.ToolStroke.getBounds(), and micropolisj.gui.MainWindow.onToolHover().
Member Data Documentation
micropolisj.engine.MicropolisTool.AIRPORT = (6, 10000)
Definition at line 34 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.BULLDOZER = (1, 1)
Definition at line 20 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar(), and micropolisj.gui.MainWindow.showToolResult().
micropolisj.engine.MicropolisTool.COMMERCIAL = (3, 100)
Definition at line 25 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
int micropolisj.engine.MicropolisTool.cost
Definition at line 41 of file MicropolisTool.java.
micropolisj.engine.MicropolisTool.FIRE = (3, 500)
Definition at line 27 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.INDUSTRIAL = (3, 100)
Definition at line 26 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.NUCLEAR = (4, 5000)
Definition at line 33 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.PARK = (1, 10)
Definition at line 30 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.POLICE = (3, 500)
Definition at line 28 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.POWERPLANT = (4, 3000)
Definition at line 32 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.QUERY = (1, 0)
Definition at line 35 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar(), micropolisj.gui.MainWindow.onToolDown(), micropolisj.gui.MainWindow.onToolDrag(), and micropolisj.gui.MainWindow.onToolHover().
micropolisj.engine.MicropolisTool.RAIL = (1, 20)
Definition at line 23 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.RESIDENTIAL = (3, 100)
Definition at line 24 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.ROADS = (1, 10)
Definition at line 22 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.ROCKET = (3, 10000)
Definition at line 37 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.MainWindow(), micropolisj.gui.MainWindow.makeToolbar(), micropolisj.gui.MainWindow.onToolDrag(), and micropolisj.gui.MainWindow.onToolUp().
micropolisj.engine.MicropolisTool.SEAPORT = (4, 3000)
Definition at line 31 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
int micropolisj.engine.MicropolisTool.size
Definition at line 40 of file MicropolisTool.java.
micropolisj.engine.MicropolisTool.STADIUM = (4, 5000)
Definition at line 29 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.TEMPEL = (6, 30000)
Definition at line 38 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.UNIVERSITY = (3, 5000)
Definition at line 36 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
micropolisj.engine.MicropolisTool.WIRE = (1, 5)
Definition at line 21 of file MicropolisTool.java.
Referenced by micropolisj.gui.MainWindow.makeToolbar().
The documentation for this enum was generated from the following file:
src/micropolisj/engine/MicropolisTool.java