Methapolis: micropolisj.engine.SpriteKind Enum Reference
micropolisj.engine.SpriteKind Enum Reference
Public Attributes
TRA = (1,5)
COP = (2,8)
AIR = (3,11)
SHI = (4,8)
GOD = (5,16)
TOR = (6,3)
EXP = (7,6)
BUS = (8,4)
ROC = (9,11)
SPACESHIP = (10, 1)
final int objectId
final int numFrames
Private Member Functions
SpriteKind (int objectId, int numFrames)
Detailed Description
Enumeration of the various kinds of sprites that may appear in the city.
Definition at line 16 of file SpriteKind.java.
Constructor & Destructor Documentation
micropolisj.engine.SpriteKind.SpriteKind (int objectId, int numFrames) private
Definition at line 32 of file SpriteKind.java.
Member Data Documentation
micropolisj.engine.SpriteKind.AIR = (3,11)
Definition at line 20 of file SpriteKind.java.
Referenced by micropolisj.engine.AirplaneSprite.AirplaneSprite(), micropolisj.engine.TornadoSprite.moveImpl(), micropolisj.engine.AirplaneSprite.moveImpl(), and micropolisj.engine.MonsterSprite.moveImpl().
micropolisj.engine.SpriteKind.BUS = (8,4)
Definition at line 25 of file SpriteKind.java.
micropolisj.engine.SpriteKind.COP = (2,8)
Definition at line 19 of file SpriteKind.java.
Referenced by micropolisj.engine.HelicopterSprite.HelicopterSprite(), micropolisj.engine.TornadoSprite.moveImpl(), micropolisj.engine.AirplaneSprite.moveImpl(), and micropolisj.engine.MonsterSprite.moveImpl().
micropolisj.engine.SpriteKind.EXP = (7,6)
Definition at line 24 of file SpriteKind.java.
Referenced by micropolisj.engine.ExplosionSprite.ExplosionSprite().
micropolisj.engine.SpriteKind.GOD = (5,16)
Definition at line 22 of file SpriteKind.java.
Referenced by micropolisj.engine.Micropolis.makeMonster(), micropolisj.engine.MonsterSprite.MonsterSprite(), and micropolisj.engine.HelicopterSprite.moveImpl().
final int micropolisj.engine.SpriteKind.numFrames
Definition at line 30 of file SpriteKind.java.
final int micropolisj.engine.SpriteKind.objectId
Definition at line 29 of file SpriteKind.java.
micropolisj.engine.SpriteKind.ROC = (9,11)
Definition at line 26 of file SpriteKind.java.
Referenced by micropolisj.engine.RocketSprite.RocketSprite().
micropolisj.engine.SpriteKind.SHI = (4,8)
Definition at line 21 of file SpriteKind.java.
Referenced by micropolisj.engine.TornadoSprite.moveImpl(), micropolisj.engine.MonsterSprite.moveImpl(), and micropolisj.engine.ShipSprite.ShipSprite().
micropolisj.engine.SpriteKind.SPACESHIP = (10, 1)
Definition at line 27 of file SpriteKind.java.
Referenced by micropolisj.engine.SpaceshipSprite.SpaceshipSprite().
micropolisj.engine.SpriteKind.TOR = (6,3)
Definition at line 23 of file SpriteKind.java.
Referenced by micropolisj.engine.Micropolis.makeTornado(), micropolisj.engine.HelicopterSprite.moveImpl(), and micropolisj.engine.TornadoSprite.TornadoSprite().
micropolisj.engine.SpriteKind.TRA = (1,5)
Definition at line 18 of file SpriteKind.java.
Referenced by micropolisj.engine.TornadoSprite.moveImpl(), micropolisj.engine.MonsterSprite.moveImpl(), and micropolisj.engine.TrainSprite.TrainSprite().
The documentation for this enum was generated from the following file:
src/micropolisj/engine/SpriteKind.java