Methapolis: micropolisj.engine.Sound Enum Reference
micropolisj.engine.Sound Enum Reference
Public Member Functions
URL getAudioFile ()
URL getAudioFile (String fileEnding)
String getWavName ()
Static Public Member Functions
static void playSound (Sound sound)
static void playSound (Sound sound, String fileEnding)
Public Attributes
EXPLOSION_LOW = ("explosion-low")
EXPLOSION_HIGH = ("explosion-high")
EXPLOSION_BOTH = ("explosion-low")
UHUH = ("bop")
SORRY = ("bop")
BUILD = ("layzone")
BULLDOZE = (null)
HONKHONK_LOW = ("honkhonk-low")
HONKHONK_MED = ("honkhonk-med")
HONKHONK_HIGH = ("honkhonk-high")
HONKHONK_HI = ("honkhonk-hi")
SIREN = ("siren")
HEAVYTRAFFIC = ("heavytraffic")
MONSTER = ("zombie-roar-5")
DUBSPLOSION = ("dubsplosion")
SPACESHIP_LAUNCH = ("missle_launch")
BG_MUSIC = ("methapolis")
String wavName
Private Member Functions
Sound (String wavName)
Detailed Description
Enumerates the various sounds that the city may produce. The engine is not responsible for actually playing the sound. That task belongs to the front-end (i.e. the user interface).
Definition at line 21 of file Sound.java.
Constructor & Destructor Documentation
micropolisj.engine.Sound.Sound (String wavName) private
Definition at line 45 of file Sound.java.
Member Function Documentation
URL micropolisj.engine.Sound.getAudioFile ()
Definition at line 49 of file Sound.java.
Referenced by micropolisj.gui.MainWindow.citySound(), and micropolisj.engine.Sound.playSound().
URL micropolisj.engine.Sound.getAudioFile (String fileEnding)
Parameters
fileEnding (String) - no dot!
Returns
Definition at line 57 of file Sound.java.
String micropolisj.engine.Sound.getWavName ()
Definition at line 86 of file Sound.java.
static void micropolisj.engine.Sound.playSound (Sound sound) static
Definition at line 63 of file Sound.java.
static void micropolisj.engine.Sound.playSound (Sound sound, String fileEnding) static
Definition at line 67 of file Sound.java.
References micropolisj.engine.Sound.getAudioFile().
Member Data Documentation
micropolisj.engine.Sound.BG_MUSIC = ("methapolis")
Definition at line 40 of file Sound.java.
Referenced by micropolisj.gui.MainWindow.MainWindow().
micropolisj.engine.Sound.BUILD = ("layzone")
Definition at line 28 of file Sound.java.
Referenced by micropolisj.gui.MainWindow.showToolResult().
micropolisj.engine.Sound.BULLDOZE = (null)
Definition at line 29 of file Sound.java.
Referenced by micropolisj.gui.MainWindow.showToolResult().
micropolisj.engine.Sound.DUBSPLOSION = ("dubsplosion")
Definition at line 38 of file Sound.java.
Referenced by micropolisj.engine.RocketSprite.moveImpl().
micropolisj.engine.Sound.EXPLOSION_BOTH = ("explosion-low")
Definition at line 25 of file Sound.java.
micropolisj.engine.Sound.EXPLOSION_HIGH = ("explosion-high")
Definition at line 24 of file Sound.java.
Referenced by micropolisj.engine.RocketSprite.explodeSprite(), micropolisj.engine.Sprite.explodeSprite(), and micropolisj.engine.ExplosionSprite.moveImpl().
micropolisj.engine.Sound.EXPLOSION_LOW = ("explosion-low")
Definition at line 23 of file Sound.java.
Referenced by micropolisj.engine.Micropolis.makeEarthquake().
micropolisj.engine.Sound.HEAVYTRAFFIC = ("heavytraffic")
Definition at line 35 of file Sound.java.
Referenced by micropolisj.engine.HelicopterSprite.moveImpl().
micropolisj.engine.Sound.HONKHONK_HI = ("honkhonk-hi")
Definition at line 33 of file Sound.java.
micropolisj.engine.Sound.HONKHONK_HIGH = ("honkhonk-high")
Definition at line 32 of file Sound.java.
micropolisj.engine.Sound.HONKHONK_LOW = ("honkhonk-low")
Definition at line 30 of file Sound.java.
Referenced by micropolisj.gui.MainWindow.citySound(), and micropolisj.engine.ShipSprite.moveImpl().
micropolisj.engine.Sound.HONKHONK_MED = ("honkhonk-med")
Definition at line 31 of file Sound.java.
micropolisj.engine.Sound.MONSTER = ("zombie-roar-5")
Definition at line 36 of file Sound.java.
Referenced by micropolisj.engine.MonsterSprite.moveImpl().
micropolisj.engine.Sound.SIREN = ("siren")
Definition at line 34 of file Sound.java.
micropolisj.engine.Sound.SORRY = ("bop")
Definition at line 27 of file Sound.java.
Referenced by micropolisj.gui.MainWindow.showToolResult().
micropolisj.engine.Sound.SPACESHIP_LAUNCH = ("missle_launch")
Definition at line 39 of file Sound.java.
Referenced by micropolisj.engine.SpaceshipSprite.moveImpl().
micropolisj.engine.Sound.UHUH = ("bop")
Definition at line 26 of file Sound.java.
Referenced by micropolisj.gui.MainWindow.showToolResult().
String micropolisj.engine.Sound.wavName
Definition at line 42 of file Sound.java.
The documentation for this enum was generated from the following file:
src/micropolisj/engine/Sound.java